### ISSUE TITLE
Error Message: This network does not exist ID: 962b56b0-99cf-4f9d-8f58-f99e96a77e48

### ISSUE THREAD

**Issue by quahchin** [IBM-Blockchain/ibm-blockchain-issues#100]
Hi, when I tried to access car_lease_blockchain from the Dashboard -> All Services section, I encountered an error message, as follows:

This network does not exist
ID: 962b56b0-99cf-4f9d-8f58-f99e96a77e48

Does anyone know what's going on? Previously it was working fine for me. Thanks and grateful for any help.

**Comment by quahchin** [comment]
Hi, problem solved! By deleting and recreating the service and the app under CF and it worked. Thanks to Liam Grace's suggestion from another issue.

**Comment by dhyey20** [comment]
@quahchin Seems that you got this figured out. If so, can you close this issue?

**Comment by cassio-rossi** [comment]
That's mean we're going to lose all data previously stored on the Blockchain ?

**Comment by dhyey20** [comment]
@kazziosoftware yes for the starter plan which is free. If you want your data to stay longer there is a HSBN plan as well.

**Comment by cassio-rossi** [comment]
@dhyey20 sorry, I didn't get it. You mean that, just because is free, any bug/update on the system, we're going to lose all data ? That's doesn't make any sense.

**Comment by dshuffma-ibm** [comment]
@kazziosoftware yep

`Starter` networks will be deleted after 15 days of inactivity in order to increase overall capacity.  "inactivity" means there are no new blocks.  Therefore all you have to do is make a single invoke every 2 weeks and your network will persist.

If this isn't appropriate for your use case you can always upgrade to HSBN.

**Comment by mrshah-at-ibm** [comment]
The solution is provided in the last comment above this.
