### ISSUE TITLE
asset management deployment issue

### ISSUE THREAD

**Issue by romanga** [IBM-Blockchain/ibm-blockchain-issues#102]
I'm trying to deploy asset_management example cloned from https://github.com/IBM-Blockchain/cp-web/tree/master/src/chaincode/vendor/github.com/hyperledger/fabric/examples/chaincode/go/asset_management and minimized to: https://github.com/romanga/hyperledger

it compiles locally and binary is produced.
when deploying to bluemix it fails with the error:
asset_management.go:26:5: cannot find package "github.com/op/go-logging" in any of:
OUT - 	/opt/gopath/src/github.com/romanga/cp-web/src/chaincode/vendor/github.com/op/go-logging (vendor tree)
OUT - 	/opt/go/src/github.com/op/go-logging (from $GOROOT)
OUT - 	/opt/gopath/src/github.com/op/go-logging (from $GOPATH)

after battling with go with no luck I commented out go-logging and now it compiles successfully, however now, it fails to init with the error:

Invalid admin certificate. Empty.

Init function requires that the metadata of the deploy transaction contains the certificate of the administrator and I found no way to pass that in the bluemix API.

**Comment by romanga** [comment]
solved the Init issue, had to pass base64 encoded tcert to init.

any suggestions on the go-logging issue?

**Comment by dshuffma-ibm** [comment]
did you try running `go get github.com/op/go-logging`?

**Comment by dshuffma-ibm** [comment]
closing, inactivity
