### ISSUE TITLE
Events are not working for 'NODE app deployed in Bluemix +  Blockchain on Bluemix starter developer plan'

### ISSUE THREAD

**Issue by venugopv** [IBM-Blockchain/ibm-blockchain-issues#104]
We are running Blockchain on Bluemix starter developer plan ( which is based on Fabric 0.6 and having network of four validating peers)

Our NODE application also running in Bluemix.

We have enabled events in Node application by connecting to eventhub by using chain.eventHubConnect API. We could see the application is successfully and deployed. 

**However when Chaincode is trying to emit an event, NODE application in Bluemix is getting crashed with the following error:**
APP/0events.js:141Apr 7, 2017 2:56:29 PM
APP/0throw er; // Unhandled 'error' eventApr 7, 2017 2:56:29 PM
APP/0Error: {"created":"@1491591389.639915488","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1491591389.639905326","description":"OS Error","errno":104,"file":"../src/core/lib/iomgr/tcp_posix.c","file_line":229,"os_error":"Connection reset by peer","syscall":"recvmsg"}]}Apr 7, 2017 2:56:29 PM
APP/0at ClientDuplexStream._emitStatusIfDone (/home/vcap/app/node_modules/grpc/src/node/src/client.js:189:19)Apr 7, 2017 2:56:29 PM
APP/0^Apr 7, 2017 2:56:29 PM
APP/0at /home/vcap/app/node_modules/grpc/src/node/src/client.js:634:14

However the same code is successfully working (i.e Chaincode can successfully emit event and NODE application getting notified with the event) in my local setup i.e both node and blockchain is in my local machine.

**And it is working successfully with NODE app deployed in my local machine.. and Blockchain on Bluemix.**

**Comment by dshuffma-ibm** [comment]
I haven't seen this before, were you able to figure it out?

**Comment by venugopv** [comment]
Hi.. still we are facing the problem.

**Comment by balakrishnaITPC** [comment]
issue fixed for me when i upgraded fabric 'hfc' library GRPC to latest module.
