### ISSUE TITLE
How to invoke chaincode from a listener code which listens to events on github using webhooks

### ISSUE THREAD

**Issue by suffiasameera** [IBM-Blockchain/ibm-blockchain-issues#106]
I am developing a code to listen to an event from github(using webhooks) and transfer it to my chaincode on Bluemix. The blockchain should be invoked by the listener code on occurence of an event. Does anybody know how to do that? Please let me know ASAP. It's really urgent. 

Thanks!

**Comment by dshuffma-ibm** [comment]
well the place to start would be to get your listener code to receive github events.  that's not something the blockchain service can help with.

as for making invokes requests, check out [marbles v3](https://github.com/IBM-Blockchain/marbles). particularly the [invoke chaincode proposal](https://github.com/IBM-Blockchain/marbles/blob/v3.0/utils/fc_wrangler/invoke_cc.js#L34) code.

**Comment by suffiasameera** [comment]
@dshuffma-ibm Yeah, I've got the listener code in place. How do I transfer the event received from github onto my blockchain using REST apis?

**Comment by suffiasameera** [comment]
Yeah, I've got the listener code in place. How do I transfer the event
received from github onto my blockchain using REST apis?

**Comment by dshuffma-ibm** [comment]
there are no REST apis for invokes in Hyperledger Fabric v1 (aka HSBN vNext). you would have to reference the marble v3 links above and use gRPC via the lastest SDK.

if you are using Hyperledger Fabric v0.6 (aka HSBN/starter) you can follow the swagger included in your service tile.  Also check out the [marbles v2.0](https://github.com/IBM-Blockchain/marbles/tree/v2.0) branch which uses the older discontinued [IBC SDK](https://github.com/IBM-Blockchain/ibm-blockchain-js) to make the invoke calls. (marbles v3 will not work on Fabric v0.6)

**Comment by suffiasameera** [comment]
@dshuffma-ibm  Okay thanks! I'll try that.
