### ISSUE TITLE
Can anyone help me with code for trasferring an event in JSON onto my blockchain?

### ISSUE THREAD

**Issue by suffiasameera** [IBM-Blockchain/ibm-blockchain-issues#107]
How do I transfer the event received from github onto my blockchain using REST apis? Please help me with the code for directly invoking the REST apis on my blockchain.

Thanks!

**Comment by dshuffma-ibm** [comment]
duplicate of https://github.com/IBM-Blockchain/ibm-blockchain-js/issues/35
