### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by codeglzhang** [IBM-Blockchain/ibm-blockchain-issues#111]
Hello, I can't understand immutability in Hyperledger. In Hyperledger, the data can not be changed even after the data is submitted to the block chain, but the data can not be changed once it is submitted to the block chain in BitCoin and Ethereum. So What is the immutability in Hyperledger?

**Comment by dshuffma-ibm** [comment]
Not sure I understand the question. Are you saying immutability is something common to BitCoin/Ethereum and it is not an advantage of Hyperledger Fabric?  If so, then I would agree with you. All blockchain technologies will have immutability, though in a proof-of-work system it takes a little more time.

If that was not your comment, could you rephrase it?
