### ISSUE TITLE
All Block chain dashboards are gone

### ISSUE THREAD

**Issue by ashwinipatankar** [IBM-Blockchain/ibm-blockchain-issues#114]
I am using bluemix, and recently I found it is not showing
![screen shot 2017-07-27 at 12 28 10 pm](https://user-images.githubusercontent.com/1446615/28658241-f0bc4da0-72c7-11e7-8ac0-a17078c3aa29.jpg)
 any block chain dashboard. Instead, it is displaying a message (screen shot attached)

**Comment by dshuffma-ibm** [comment]
the starter plan is no more. its beta is over. there is a [new plan](https://console.bluemix.net/developer/blockchain/dashboard).
