### ISSUE TITLE
My blockchain network was gone

### ISSUE THREAD

**Issue by Aaron-Zhou** [IBM-Blockchain/ibm-blockchain-issues#115]
Got this error when tried to access fabric dashboard: 
This network does not exist
ID: b4ccbc36-0450-4b9b-b019-1010cc1e070e

I created a 0.6 starter version of fabric from bluemix US south. But it seems down now.

**Comment by mrshah-at-work** [comment]
Looks like your network was not used for more than 15 days. Thus it got deleted.

**Comment by Aaron-Zhou** [comment]
There's no alert that my network will be removed. That's really a big surprise. Is there anyway to get network back? I have lost all data I created.

**Comment by dshuffma-ibm** [comment]
all starter networks have been retired, the data cannot be retrieved.
