### ISSUE TITLE
clicking RESTART button causes peer to crash, and cannot restart

### ISSUE THREAD

**Issue by scottz64** [IBM-Blockchain/ibm-blockchain-issues#12]
I created a new IBM ID, logged in to BlueMix and started a new Blockchain demo network with 5 peers.

- The "Network" tab shows CA and 4 peers running. 
- On the "Demo Chaincode" tab, clicking Invoke/Query for Example02 works fine.
- On the Network tab, I clicked Restart for VP2. After some time, it shows "Stopped" in the Status column. 
- It was really stopped, and could not be recovered by clicking "restart" again. 
- Also, at that point, I confirmed it was down by clicking "Stop" for VP1, and trying Invokes and Queries which verified that the consensus network was halted. 
- Restarting VP1 plus Invokes/Queries worked fine to show consensus resumed. [HOWEVER, after restarting VP1, it still showed "Stopped" in the Status column, even after half hour.]

Expected behavior:
1. The restart arrow/button should not be active when the node is running. Only the stop action should be active.
2. Since it is active, clicking it should restart the node, and it should resume to the Running state after a couple minutes.
3. It should not stay down forever, but it does. Reloading the page does not change anything.
4. Clicking Restart for that node (the button is active) should recover the node, but it does not.

Network ID: 40a50047-79f7-49a9-98ed-066031992215
https://obc-service-broker-prod.mybluemix.net/v2/monitor/40a50047-79f7-49a9-98ed-066031992215

**Comment by dshuffma-ibm** [comment]
fixed, try it again

**Comment by scottz64** [comment]
After a long time (minutes) when it appeared Stopped (and no progress message indicated anything different), it did finally return to "Running" state and behave correctly.
