### ISSUE TITLE
cannot delete old blockchain network service from bluemix production environment

### ISSUE THREAD

**Issue by scottz64** [IBM-Blockchain/ibm-blockchain-issues#124]
![screenshot2018-04-20cannotdeleteoldnetworkservice](https://user-images.githubusercontent.com/19557276/39066701-f1b477b0-44a3-11e8-9ed1-d3b3d66b3fad.png)

I had created a blockchain network months ago: Blockchain-scottz_org_1-hsbn
Today I am unable to delete the bluemix service. Attached is screenshot with the error message `This blockchain does not exist`. How can I delete the bluemix service? Please help.

**Comment by scottz64** [comment]
Also, from that page shown, when I click the 3 dots and select "delete service", I get the error message:

`Error`
`Service instance Blockchain-scottz_org_1-hsbn: Service broker error: {"description"=>"Internal error finding the service instance to delete"}`

**Comment by ztanaka1971** [comment]
I have same problem, too.

> Error 10001
> Description:
> Service instance car_lease_blockchain: Service broker error: {"description"=>"Internal error finding the service instance to delete"}

**Comment by mrshah-at-work** [comment]
Can you please open a ticket and IBM Cloud will be able to override and help you delete the service instance.

**Comment by ztanaka1971** [comment]
Thank you, I opened ticket and the services were deleted !
