### ISSUE TITLE
Service Credentials - Broken Link to cert

### ISSUE THREAD

**Issue by bmos299** [IBM-Blockchain/ibm-blockchain-issues#13]
Using the node sdk we need the CA cert from the Service Credentials.

In the file there is a link to the cert:
}
],
"cert": "https://certs.blockchain.ibm.com/blockchain.ibm.com.cert"
}
}

However, when I go to the url I get:

503 Service Unavailable
nghttpx nghttp2/1.12.0

**Comment by dshuffma-ibm** [comment]
Known issue, we will have this resolved shortly. The url is really a placeholder, we will host it soon.

**Comment by bmos299** [comment]
Thanks.

**Comment by dshuffma-ibm** [comment]
Ok fixed. In Bluemix you will need to delete the current credentials and then click "ADD CREDENTIALS" for the new link to appear.

![image](https://cloud.githubusercontent.com/assets/16085295/17308894/1cbea26a-580a-11e6-989c-b1a3ef05991c.png)

**Comment by bmos299** [comment]
Thanks David.
