### ISSUE TITLE
Orderer bootstrap fails

### ISSUE THREAD

**Issue by yousaf101** [IBM-Blockchain/ibm-blockchain-issues#130]
Orderer container is not being bootstraped and exiting. I have checked the orderer logs and have found this error. Any solution?

"Error creating channelconfig bundle: cannot enable channel capabilities without orderer support first"

**Comment by mrshah-at-work** [comment]
looks like you are trying to use some capabilities when creating a channel and these capabilities are not enabled in the orderer?

**Comment by yousaf101** [comment]
Can you tell me that where to enable these capabilities in the orderer? I
mean which file i need to configure to enable these capabilities in the
orderer?

**Comment by kalop** [comment]
Have you solved this issue? I'm in the same point

**Comment by mrshah-at-work** [comment]
@kalop @youdsf0 can you guys let me know what instructions are you following to get to this point? Maybe I can help fix the instructions.

**Comment by sahooch** [comment]
I am facing same issue > is any solution exist

**Comment by mrshah-at-work** [comment]
@sahooch can you tell me how you reached the issue? What are you trying to do and what instructions are you following?

**Comment by darwinharianto** [comment]
Got this issues, I fixed it by looking at configtx.yaml.
There are some problems with my spacing and untyped rules.
once it is fixed, recreating the block and channeltx file will fix it.

**Comment by mrshah-at-work** [comment]
I am going to close this issue as no one wants to point to the root of the issue where this all started.
