### ISSUE TITLE
Blockchain createchannel container is never completed

### ISSUE THREAD

**Issue by dontAskVI** [IBM-Blockchain/ibm-blockchain-issues#131]
Hello!

I've tried multiple times to get my sample Blockchain network setup, but I never get through all of the steps successfully. I've tried to do this locally and onto Bluemix, but I am still not having much luck. The stage I'm currently stuck at is as follows:

* export Kubernetes config
* run the create_all.sh script
* 'Waiting for createchannel container to be Completed' is repeated over and over again. I've left this for half an hour and it just keeps printing the same log to my terminal.

Command `kubectl logs createchannel createchanneltx` gives me:
```
/shared
configtx.yaml
crypto-config
status_cryptogen_complete
2019-02-02 16:48:03.085 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2019-02-02 16:48:03.502 UTC [common/tools/configtxgen/localconfig] Load -> PANI 002 Could not find profile:  TwoOrgsChannel
2019-02-02 16:48:03.502 UTC [common/tools/configtxgen] func1 -> ERRO 003 Could not find profile:  TwoOrgsChannel. Please make sure that FABRIC_CFG_PATH or --configPath is set to a path which contains configtx.yaml with the specified profile
```

Tried to delete with `./delete_all.sh -i` and create again with `./create_all.sh`, but nothing really changed.

Command `kubectl logs createchannel createchannel` returns `Waiting for channeltx`.

Also command `cat fabric-cluster.yml` shows that the file is empty.

How do I get past this step?

**Comment by mallapurbharat** [comment]
I'm facing this exact same issue as well. Can someone help out here?

**Comment by mrshah-at-work** [comment]
Can you please tell us what code are you using to setup the blockchain network?

**Comment by mallapurbharat** [comment]
Sorry, but I'm new to this entire IBM cloud and K8s creation of fabric instances.
I was using the repository at https://github.com/SaifRehman/fabric-evm-ibm-container-service.git as mentioned in the article https://medium.com/coinmonks/ethereum-and-fabric-crossover-deploying-ethereum-smart-contract-on-hyperledger-fabric-blockchain-fe937e2e3680

I found the problem. It looks like the configtx.yaml file in the container createchannel:/etc/hyperledger/fabric/configtx.yaml doesn't have the TwoOrgsChannel profile listed in it.

I tried copying a configtx.yaml with the TwoOrgsChannel details to the container folder but it gets replaced in the next run of the scripts.

I will try using Swetha Repakula's git repository (https://github.com/swetharepakula/fabric-evm-ibm-container-service) for this and update whether this solves the problem.

**Comment by mallapurbharat** [comment]
Ok... there is a compatibility issue with Swetha Repakula's code base (https://github.com/swetharepakula/fabric-evm-ibm-container-service) since IBM Cloud now uses Kubernetes 1.11.x which internally uses containerd instead of docker. The code base will not deploy successfully due to this issue.

**Comment by mrshah-at-work** [comment]
Correct, please reach out to maintainers of the repository that you mentioned above. And please open issues on that repository to follow up. Sorry, we cannot help with the private repository.

Thanks for understanding.
