### ISSUE TITLE
SDK cannot connect to proxy using TLS: Bad GRPC frame type 0x<##>

### ISSUE THREAD

**Issue by rennman** [IBM-Blockchain/ibm-blockchain-issues#14]
(moved from obc  #244)

I'm trying to do a simple 'register' using the node sdk to a bluemix-hosted blockchain network.

On z, I get:
   Bad GRPC frame type 0x45

On x86, I get:
   Bad GRPC frame type 0x3c

I don't have direct access to the x86 internal network, but if I bypass the proxy server on z, the registration is successful:
Mon, 01 Aug 2016 17:15:30 GMT hfc Enrolling [req={"enrollmentID":"admin","enrollmentSecret":"b41c0e567b"}]
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] [{"enrollmentID":"admin","enrollmentSecret":"b41c0e567b"}]
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] Generating keys...
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] Generating keys...done!
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d03010703420004738e85b81c7871092d49ccbb0968ca2d35d831afe23943c8b5188fd83d92d6fb3e0f6db809f4ce2ea8d2d0d6d0d149ee4e6f2345ef95f31fe2d70017cb2be8b6"
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] Adding signing key!
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] Assding encryption key!
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1470071730,"high":0,"unsigned":false},"nanos":0},"id":{"id":"admin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[98,52,49,99,48,101,53,54,55,98]},"offset":0,"markedOffset":-1,"limit":10,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,115,142,133,184,28,120,113,9,45,73,204,187,9,104,202,45,53,216,49,175,226,57,67,200,181,24,143,216,61,146,214,251,62,15,109,184,9,244,206,46,168,210,208,214,208,209,73,238,78,111,35,69,239,149,243,31,226,215,0,23,203,43,232,182]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,124,62,254,153,232,36,54,246,79,231,161,132,9,193,182,137,11,89,99,123,99,57,195,70,85,196,122,52,212,147,120,171,37,110,224,201,88,140,40,31,39,138,164,155,22,92,231,27,56,123,111,174,2,210,207,193,16,199,244,129,195,181,205,84]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null} 
Mon, 01 Aug 2016 17:15:30 GMT hfc [MemberServicesImpl.enroll] eCertCreateResp : [%j][object Object]
Mon, 01 Aug 2016 17:15:30 GMT hfc [memberServices.enroll] err=null, enrollment={"key":"68a7a6c595545784046d0ede6d73fb9b83b2edd54924f462d5fd4c3b7988905b","cert":"308201b130820156a003020102020101300a06082a8648ce3d0403033031310b300906035504061302555331143012060355040a130b48797065726c6564676572310c300a06035504031303656361301e170d3136303830313137313433305a170d3136313033303137313433305a3040310b300906035504061302555331143012060355040a130b48797065726c6564676572311b301906035504030c1261646d696e5c67726f7570315c30303032333059301306072a8648ce3d020106082a8648ce3d03010703420004738e85b81c7871092d49ccbb0968ca2d35d831afe23943c8b5188fd83d92d6fb3e0f6db809f4ce2ea8d2d0d6d0d149ee4e6f2345ef95f31fe2d70017cb2be8b6a350304e300e0603551d0f0101ff040403020780300c0603551d130101ff04023000300d0603551d0e0406040401020304300f0603551d2304083006800401020304300e06065103040506070101ff040131300a06082a8648ce3d04030303490030460221008654ff94e13ab352fe1d197ee31d8bea7d3d9a0ef7ffee2fc9845720b35eec20022100d7ffce53b3f2e8c684faaac57a988f5ab3b1a2ac948dfb38d7415f5794faeda8","chainKey":"2d2d2d2d2d424547494e204543445341205055424c4943204b45592d2d2d2d2d0a4d466b77457759484b6f5a497a6a3043415159494b6f5a497a6a3044415163445167414541456d6a384731463142664d5030576b53504c7569624f72714576390a346e354d597a584d5778465278536a4d7072533644337638354c7a722b735455396774676a7a4c70776a4352544f6c39306b424f6c79676351513d3d0a2d2d2d2d2d454e44204543445341205055424c4943204b45592d2d2d2d2d0a"}

If I send exactly the same request, but send it to the proxy instead of the zaci address (b98b6324-a7a9-4fd6-90d4-342383746893_ca-api.zone.blockchain.ibm.com), I get this:
Mon, 01 Aug 2016 18:37:33 GMT hfc Enrolling [req={"enrollmentID":"admin","enrollmentSecret":"b41c0e567b"}]
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] [{"enrollmentID":"admin","enrollmentSecret":"b41c0e567b"}]
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] Generating keys...
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] Generating keys...done!
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d03010703420004989b9ad0648aef83e3e0b314ad0da105ace688a65833202feeddf2067bef03afcd9f3aae9844901028ca673fcd54e1da23f304b3ba0bee7e528b35d422467ae2"
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] Adding signing key!
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] Assding encryption key!
Mon, 01 Aug 2016 18:37:33 GMT hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1470076653,"high":0,"unsigned":false},"nanos":0},"id":{"id":"admin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[98,52,49,99,48,101,53,54,55,98]},"offset":0,"markedOffset":-1,"limit":10,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,152,155,154,208,100,138,239,131,227,224,179,20,173,13,161,5,172,230,136,166,88,51,32,47,238,221,242,6,123,239,3,175,205,159,58,174,152,68,144,16,40,202,103,63,205,84,225,218,35,243,4,179,186,11,238,126,82,139,53,212,34,70,122,226]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,223,245,90,228,122,56,34,99,229,254,253,249,183,87,245,148,181,78,62,83,99,41,81,206,37,173,33,8,219,87,130,134,74,59,154,54,9,46,97,107,47,98,179,66,240,215,147,230,116,84,167,223,194,79,67,231,37,68,104,158,232,154,125,211]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null} 
E0801 14:37:34.325239654   23954 frame_data.c:168]           Bad GRPC frame type 0x45

**Comment by dshuffma-ibm** [comment]
Try changing the grpc module that HFC uses from 0.13.0 to 1.0.0-pre1 in the package.json of HFC.

**Comment by rennman** [comment]
Thanks, Dale and I tried that, which solved the GRPC errors, but the proxy is now returning '302' errors. He's looking into that.

**Comment by dshuffma-ibm** [comment]
For anyone else that finds this issue, we now have this guide.

https://github.com/IBM-Blockchain/ibm-blockchain-issues/tree/master/hfc_help

**Comment by rennman** [comment]
I cloned the master branch and installed node modeule hfc version 0.6.
I confirmed in the dependencies that "grpc" os set to "1.0.0-pre1".

I'm no longer getting 'Bad frame' errors on the x68 BMX, but am getting HTTP 302 errors.


However, on z, I am getting 'Bad GRPC frame type 0x45'

Here's a snippet, but I will attach the entire GRPC_TRACE
E0802 13:35:56.384994282    3132 parsing.c:968]              {"created":"@1470159356.384974588","description":"Bad GRPC frame type 0x45","file":"../src/core/ext/transport/chttp2/transport/frame_data.c","file_line":185,"offset":0,"raw_bytes":"45 72 72 6f 72 3a 20 52 6f 75 74 65 20 4e 6f 74 20 46 6f 75 6e 64 'Error: Route Not Found'","stream_id":1}
D0802 13:35:56.385028947    3132 chttp2_transport.c:1888]    set connectivity_state=4
D0802 13:35:56.385056469    3132 connectivity_state.c:156]   SET: 0x7fc60c025480 client_transport: READY --> SHUTDOWN [close_transport] error=0x7fc60c011230 {"created":"@1470159356.385012818","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1789,"grpc_status":14,"referenced_errors":[{"created":"@1470159356.384974588","description":"Bad GRPC frame type 0x45","file":"../src/core/ext/transport/chttp2/transport/frame_data.c","file_line":185,"offset":0,"raw_bytes":"45 72 72 6f 72 3a 20 52 6f 75 74 65 20 4e 6f 74 20 46 6f 75 6e 64 'Error: Route Not Found'","stream_id":1}]}
D0802 13:35:56.385213880    3132 connectivity_state.c:156]   SET: 0x7fc614002d28 (null): READY --> SHUTDOWN [selected_changed] error=0x7fc60c011230 {"created":"@1470159356.385012818","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1789,"grpc_status":14,"referenced_errors":[{"created":"@1470159356.384974588","description":"Bad GRPC frame type 0x45","file":"../src/core/ext/transport/chttp2/transport/frame_data.c","file_line":185,"offset":0,"raw_bytes":"45 72 72 6f 72 3a 20 52 6f 75 74 65 20 4e 6f 74 20 46 6f 75 6e 64 'Error: Route Not Found'","stream_id":1}]}
D0802 13:35:56.385244744    3132 connectivity_state.c:156]   SET: 0x7fc614003618 subchannel: READY --> SHUTDOWN [reflect_child] error=0x7fc60c011230 {"created":"@1470159356.385012818","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1789,"grpc_status":14,"referenced_errors":[{"created":"@1470159356.384974588","description":"Bad GRPC frame type 0x45","file":"../src/core/ext/transport/chttp2/transport/frame_data.c","file_line":185,"offset":0,"raw_bytes":"45 72 72 6f 72 3a 20 52 6f 75 74 65 20 4e 6f 74 20 46 6f 75 6e 64 'Error: Route Not Found'","stream_id":1}]}
I0802 13:35:56.385251363    3132 http_client_filter.c:103]   Unexpected content-type 'text/html; charset=utf-8'

**Comment by rennman** [comment]
[grpc.err.txt](https://github.com/IBM-Blockchain/ibm-blockchain-issues/files/397732/grpc.err.txt)

**Comment by rennman** [comment]
I got the same results with the hlc v0.5 version using the v0.5 preview branch

**Comment by rennman** [comment]
I now have an active HSBN using z on the back end. I have 0.5.0 hfc and v0.5 preview branch.

The registration and enrollment is working, but the deploys are failing, even with the certificate fix that was added by https://github.ibm.com/IBM-Blockchain/z-dev/issues/171.

I verified that the generated tar file contains the correct certificate and all associated src code files.

**Comment by rennman** [comment]
Since the original issue has been resolved, I'm spawning a new issue.
