### ISSUE TITLE
Status indicates Stopped after stop and restart VP

### ISSUE THREAD

**Issue by scottz64** [IBM-Blockchain/ibm-blockchain-issues#15]
- On BlueMix simple free network of 5 peers:
- On Network tab, click Stop action for VP2. Wait minutes. On status column, it shows "Stopped" for VP 2.
- On Network tab, click Restart action for VP2. (I tried with 2 different VPs. Reproduced both.) Wait minutes. **On status column, it STILL shows "Stopped" for VP 2.** Other testing (stopping an additional peer and try more invokes/queries) confirmed that the node had recovered and is in fact running and is part of the consensus network, so this appears to be merely a display problem.

**Comment by scottz64** [comment]
Clafification: this is not only a display problem, when you think about what can be done next.

Because the STOP action button is also deactivated whenever the status shows Stopped, then (even though the restarted peer is working) I can no longer stop it.

**Comment by dshuffma-ibm** [comment]
When you send queries/invoke is it through HTTP or gRPC? I have a feeling only HTTP is down after a "stop"/"restart".

**Comment by scottz64** [comment]
I am simply using the buttons on the "Demo Chaincode" tab, clicking Invoke/Query for Example02.

**Comment by dshuffma-ibm** [comment]
fixed, try it again

**Comment by scottz64** [comment]
After a few minutes, it does recover and behave correctly.
