### ISSUE TITLE
Can't find TLS certificate for chaincode container on SDK deploy

### ISSUE THREAD

**Issue by rennman** [IBM-Blockchain/ibm-blockchain-issues#17]
Using the SDK to deploy. There is an inconsistency in the name of the certificate that the peer expects to find in the chaincode container.

The SDK was updated to include the TLS certificate in the Docker tar file set to the peer during a deploy request per z-dev issue  https://github.ibm.com/IBM-Blockchain/z-dev/issues/171.

The fix requires the user to
1) put the CA cert file in the chaincode diretory.
2) update the SDK deploy request with the name of the directory into which the certificate will be copied. ("/root")

The certificate is copied as "certificate.pem" since this is the filename that the server expects to find.

However, on the starter blockchain on x86, the certificate is expected to be named 'blockchain-cert.pem', and cannot find the certificate.pem file.

The SDK should be agnostic w/r/t to the system hosting the peer network. Putting logic in the sdk utility to conditionally rename to cert depending on the peer environment doesn't make sense. The code that spins up the chaincode container in network mode should work the same, regardless of the underlying OS.

**Comment by bmos299** [comment]
This is a blocker, With out fix for this issue , users cannot really use Node SDK as Deploy itself fails.

**Comment by ratnakar-asara** [comment]
This is a blocker, without fix for this issue users cannot really use Node SDK as deploy on Bluemix fails

**Comment by dshuffma-ibm** [comment]
Its hardly a blocker, though it is inconvenient.  Just rename the cert you downloaded to `certificate.pem`.

[Its Step 8](https://github.com/IBM-Blockchain/ibm-blockchain-issues/tree/master/hfc_help)

unless i'm missing something?

**Comment by ratnakar-asara** [comment]
@dshuffma-ibm , As @rennman mentioned above , 

> the starter blockchain on x86, the certificate is expected to be named 'blockchain-cert.pem', and cannot find the certificate.pem file

User/Customer has to make a change in node sdk library (in hfc.js) from **certificate.pem** to **blockchain-cert.pem** in the below line:

```
 dockerFileContents = dockerFileContents + "\n" + "COPY certificate.pem %s";
```

@rennman , Could you please confirm.

**Comment by bmos299** [comment]
Short-term, asking someone to go in and change the hfc.js, isn't what we want to tell customers who call in.  We have over 1000 users on the starter network and right now none of them can use hfc.js.   Longer term, there are some others issues we can discuss.

**Comment by dshuffma-ibm** [comment]
guys slow down, no one has to edit hfc.  Follow the [guide](https://github.com/IBM-Blockchain/ibm-blockchain-issues/tree/master/hfc_help) and all is well.

the bluemix networks have no expectation of a cert to be named anything.  hfc however does expect the cert to be named a certain way. since it builds a docker file for your chaincode using `certifcate.pem`

**Comment by rennman** [comment]
Confirming that modifying the deploy request to include the full path to include the certificate name, and not just the directory is sufficient to set the correct cert file:
var deployRequest = {
    fcn: "init",
    args: ["a", initA, "b", initB],
    **certificatePath: "/certs/blockchain-cert.pem"**
  };

However, @ratnakar-asara has made the argument that any given app should work in either env without modification. https://github.ibm.com/IBM-Blockchain/z-dev/issues/263
