### ISSUE TITLE
CA and VPs not running upon creating a new service

### ISSUE THREAD

**Issue by koszarskyb1** [IBM-Blockchain/ibm-blockchain-issues#19]
After starting up 10 networks, the results were as follows:

No Ca, 0 peers
No Ca, 1 peer
Ca, 2 peers
No Ca, 4 peers
No Ca, 2 peers
Ca, 3 peers
Ca, All 4 peers
No Ca, 0 peers
Ca, 0 peers
Ca, All 4 peers

so 2 of the 10 are fully functional

Furthermore, when attempting to restart the stopped Ca/peers the network freezes (refresh clock stops) and a restart does not occur.

**Comment by sidrmsh** [comment]
Having the same issue, here is my error report after running the service 10 times:

1-4: failed to start any peers (only CA was up and the rest were stopped)
5: 3 peers and CA were up and running
6-9: failed again (same issue as 1-4)
10: VP0, VP1, VP2 and CA were up and running, but not VP3

PS: tried restarting some peers at random, but that didn't help.

**Comment by kramasundar** [comment]
Hi,

same issue here... some VPs are down randomly... (started a new service to confirm the same)... restart doesn't help...

Please fix...

thanks
Ram

**Comment by dshuffma-ibm** [comment]
Thanks for the report! We were already aware and are investigating.

**Comment by kramasundar** [comment]
Thanks for the fix guys!

**Comment by dshuffma-ibm** [comment]
Update: Most networks are back, we are still restarting some peers. Creating new networks is on hold for now.

**Comment by mastersingh24** [comment]
I am closing this as I believe that with the new checks @dshuffma-ibm  added we are in good shape
