### ISSUE TITLE
Querying the (learn-chaincode) chaincode fails

### ISSUE THREAD

**Issue by kramasundar** [IBM-Blockchain/ibm-blockchain-issues#20]
Hi,

I have deployed the code given below and it was successful but when i try to query i get an error "Error:Failed to launch chaincode spec(Could not get deployment transaction for ..........."

The complete req/res set are given below.

Please help me to understand what is wrong...

Thanks
Ram
# `Deploy:

{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID": {
      "path": "https://github.com/kramasundar/learn-chaincode/finished"
    },
    "ctorMsg": {
      "function": "init",
      "args": [
        "hi there"
      ]
    },
    "secureContext": "user_type1_9e92610ab3"
  },
  "id": 1
}

Curl
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"jsonrpc\": \"2.0\",
  \"method\": \"deploy\",
  \"params\": {
    \"type\": 1,
    \"chaincodeID\": {
      \"path\": \"https://github.com/kramasundar/learn-chaincode/finished\"
    },
    \"ctorMsg\": {
      \"function\": \"init\",
      \"args\": [
        \"hi there\"
      ]
    },
    \"secureContext\": \"user_type1_9e92610ab3\"
  },
  \"id\": 1
}" "https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp1.us.blockchain.ibm.com:443/chaincode"

Request URL
https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp1.us.blockchain.ibm.com:443/chaincode

Response Body
{
  "jsonrpc": "2.0",
  "result": {
    "status": "OK",
    "message": "cfa4c2a2b83e296526d2ea3a2e03ef0065a69605a4c01a8111571d7de0704a2d67a7ec01952243ef0b214a7bce0dc0d53733e32dc43c796b95a923bb8348e014"
  },
  "id": 1
}

Response Code
200

Response Headers
{
  "content-type": "application/json"
}
# Query:

 {
      "jsonrpc": "2.0",
      "method": "query",
      "params": {
          "type": 1,
          "chaincodeID": {
              "name": "cfa4c2a2b83e296526d2ea3a2e03ef0065a69605a4c01a8111571d7de0704a2d67a7ec01952243ef0b214a7bce0dc0d53733e32dc43c796b95a923bb8348e014"
          },
          "ctorMsg": {
              "function": "read",
              "args": [
                  "hello_world"
              ]
          },
          "secureContext": "user_type1_9e92610ab3"
      },
      "id": 2
  }

Curl
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
      \"jsonrpc\": \"2.0\",
      \"method\": \"query\",
      \"params\": {
          \"type\": 1,
          \"chaincodeID\": {
              \"name\": \"cfa4c2a2b83e296526d2ea3a2e03ef0065a69605a4c01a8111571d7de0704a2d67a7ec01952243ef0b214a7bce0dc0d53733e32dc43c796b95a923bb8348e014\"
          },
          \"ctorMsg\": {
              \"function\": \"read\",
              \"args\": [
                  \"hello_world\"
              ]
          },
          \"secureContext\": \"user_type1_9e92610ab3\"
      },
      \"id\": 2
  }" "https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp1.us.blockchain.ibm.com:443/chaincode"

Request URL
https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp1.us.blockchain.ibm.com:443/chaincode

Response Body
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for cfa4c2a2b83e296526d2ea3a2e03ef0065a69605a4c01a8111571d7de0704a2d67a7ec01952243ef0b214a7bce0dc0d53733e32dc43c796b95a923bb8348e014 - LedgerError - ResourceNotFound: ledger: resource not found)"
  },
  "id": 2
}

Response Code
200

Response Headers
{
  "content-type": "application/json"
}`

**Comment by kramasundar** [comment]
Hi,

it seems that there is a general issue (at least for my account?)  with "query" requests...

I deployed the "Example02" from the "Demo Chaincode" section, and then i tried to query with the action button "Query A".... which failed as well...

Given below is the output from the page...

`
Registering enrollID dashboarduser_type1_a1542a9c95 
  HTTP POST https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp0.us.blockchain.ibm.com:443/registrar
{
    "enrollId": "dashboarduser_type1_a1542a9c95",
    "enrollSecret": "c3a8e2cee1"
} 
  Success - registering enrollID 
    Response
{
    "OK": "Login successful for user 'dashboarduser_type1_a1542a9c95'."
} 

Deploying chaincode https://github.com/masterDev1985/hyperledger_chaincode/chaincode_example02 
  HTTP POST https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp0.us.blockchain.ibm.com:443/chaincode
{
    "jsonrpc": "2.0",
    "method": "deploy",
    "params": {
        "type": 1,
        "chaincodeID": {
            "path": "https://github.com/masterDev1985/hyperledger_chaincode/chaincode_example02"
        },
        "ctorMsg": {
            "function": "init",
            "args": [
                "a",
                "100",
                "b",
                "200"
            ]
        },
        "secureContext": "dashboarduser_type1_a1542a9c95"
    },
    "id": 1
} 
  Success - deployment (wait for the cc to start up)... 
    Response
{
    "jsonrpc": "2.0"
    "result": {
        "status": "OK"
        "message": "72c3c395707be7da6e26841bb9475ec96ac06687cdf5ea55796202801e658d0bafe257109ec7eebd1814ca5c76b8be5f03d3233b704fd297e8fcb81dbab7305e"
    }
    "id": 1
} 

  done 
Querying function - query ["a"] 
  HTTP POST https://828adc0e-fc3d-4cad-be7a-9ea9a5409545_vp0.us.blockchain.ibm.com:443/chaincode
{
    "jsonrpc": "2.0",
    "method": "query",
    "params": {
        "type": 1,
        "chaincodeID": {
            "name": "72c3c395707be7da6e26841bb9475ec96ac06687cdf5ea55796202801e658d0bafe257109ec7eebd1814ca5c76b8be5f03d3233b704fd297e8fcb81dbab7305e"
        },
        "ctorMsg": {
            "function": "query",
            "args": [
                "a"
            ]
        },
        "secureContext": "dashboarduser_type1_a1542a9c95"
    },
    "id": 1
} 
  Error - undefined 
    Response
{
    "jsonrpc": "2.0"
    "error": {
        "code": -32003
        "message": "Query failure"
        "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 72c3c395707be7da6e26841bb9475ec96ac06687cdf5ea55796202801e658d0bafe257109ec7eebd1814ca5c76b8be5f03d3233b704fd297e8fcb81dbab7305e - LedgerError - ResourceNotFound: ledger: resource not found)"
    }
    "id": 1
} 
`

**Comment by dshuffma-ibm** [comment]
you are waiting after deploying cc right? it can take as much as 2 minutes for chaincode to deploy.  after deploying you should wait 1-2 minutes, or so before sending a query.

the details you posted look fine, maybe you are just having bad luck.  delete this network and try another.

**Comment by kramasundar** [comment]
Yeah... I created a new network and it is fine now (BTW earlier i didn't know about the 2 mins cool off period. But got that from some documentation)

Thanks for your time!

**Comment by dongpengfei** [comment]
@kramasundar 

Hi, 
I meet the same error, error msg as :
```
Error: Error querying chaincode: rpc error: code = 2 desc = Error:Failed to launch chaincode spec(Could not get deployment transaction for ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539 - LedgerError - ResourceNotFound: ledger: resource not found)
```

Can you tell me details about your solution ? Especially, how to created new network.

My case is CLI.

**Comment by masterDev1985** [comment]
To 'create a new network', you simply provision a new instance of the blockchain service on Bluemix.  The solution that @dshuffma-ibm describes is simply to wait longer for the network to finish deploying the chaincode.  Even though the deployment response comes back with a chaincode ID relatively quickly, it still takes a few minutes for the chaincode to actually become ready.  Assuming that your chaincode is good (we already know chaincode example 02 is fine), then waiting longer should do the trick.

**Comment by dongpengfei** [comment]
@masterDev1985 

Thanks.

Your solution is right.
Yesterday, I had tried to wait longer. And I found the containers not to start. The container's status is exited, as follow:

![04p ss6xk7 5 w4d n_puv](https://cloud.githubusercontent.com/assets/1546140/20953347/d67ad79c-bc6d-11e6-97a4-4868aa71c11e.png)

I'm searching for the reason.

It would be great if you could help me again.

**Comment by mrshah-at-work** [comment]
Can you print the logs of the chaincode container?
`docker logs 43194450`

It might be because the chaincode container cannot communicate with the peer or it might be exiting due to some error in chaincode.
