### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by shireesh18** [IBM-Blockchain/ibm-blockchain-issues#23]
Hi am receiving the below error while trying to deploy my chaincode . I have followed the steps from the [URL](https://github.com/IBM-Blockchain/learn-chaincode) with out any issues until this point.

Error Response:

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Deployment failure",
    "data": "Error when deploying chaincode: Failed loading TCerts from TCA"
  },
  "id": 1
}

**Comment by shireesh18** [comment]
Able to get the response back after stopping the other peers and just allowing peer1 to start.  Not sure if this how it is supposed to work or its a bug

**Comment by shireesh18** [comment]
Now I get the below error response when I invoke query

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for XXXX - LedgerError - ResourceNotFound: ledger: resource not found)"
  },
  "id": 2
}

**Comment by shireesh18** [comment]
I do not have any issues with invokespec, deployspec . Its only the query spec keep giving me issues. Can some one please help ??

**Comment by mrshah-at-work** [comment]
It means that the chaincode was not deployed properly. Possible reasons:
1. Chaincode is not compiling
2. Docker endpoint issues deploying chaincode 

Can you verify if the deployment transaction was successful? Try to find the status of the transaction id that is returned after deploy.
