### ISSUE TITLE
Suggestions on accessing the Events api to hyperledger on bluemix

### ISSUE THREAD

**Issue by zmanian** [IBM-Blockchain/ibm-blockchain-issues#24]
If I wanted to have an Events consumer access the hyperledger network, how would I go about that?

I'm not sure how the Events consumer api interacts with the CA, there doesn't look like an obvious place to provide  a credential.

**Comment by dshuffma-ibm** [comment]
I don't have any experience using the events based APIs. You may want to ask this question on the [fabric](https://github.com/hyperledger/fabric/issues) and mention HFC and/or node sdk in the title.

**Comment by mastersingh24** [comment]
@zmanian  - for the Bluemix services, we did not enable the event listener API endpoint for either of the plans (starter and high security).  We have it on the roadmap to enable it for both service plans

**Comment by zmanian** [comment]
Thanks. That's really helpful to know.

**Comment by dhyey20** [comment]
Closed due to inactivity. 
On a side note as of 10-Nov our new version has the event ports enabled for bluemix starter plan.
