### ISSUE TITLE
logging in as another user and got "You don't have access to this dashboard"

### ISSUE THREAD

**Issue by ratnakar-asara** [IBM-Blockchain/ibm-blockchain-issues#26]
Slightly different from issue  #2

**"whoops"** error message shown, right after creating a new starter network from Bluemix

_"You don't have access to this dashboard"_

I have seen this issue when I switch between two Bluemix accounts.

How to reproduce: 
1. Login from Chrome to bluemix with **user-1**
2. Do some operations (create network and use credentials for testing)
3. Logout and Login this time with a new user **user-2**
4. **Whoops** error message is shown right after creating a network and No option is available to see the Dashboard
   ![whoops_message](https://cloud.githubusercontent.com/assets/18034452/17951522/bc1cd678-6a30-11e6-8a34-a195f438fedc.png)
5. Switch to different browser (Firefox) and login and the network created in previous step is accessible now.

**NOTE**: As a workaround using different browsers (Firefox/Chrome) for different users.

**Firfox version**:
![firfox_version](https://cloud.githubusercontent.com/assets/18034452/17951527/c710f208-6a30-11e6-9b77-3711cb6f4cc8.png)

**Chrome version**:
![chrome_version](https://cloud.githubusercontent.com/assets/18034452/17951541/e8148a6e-6a30-11e6-91e5-84f0289c343b.png)

**Comment by dshuffma-ibm** [comment]
So to recap if you login as one user then logout and login as another user then try to access the second user's dashboard you get the whoops error.

Short term fix is: don't do this. close your browser or use differently browsers when switching IBM ID users.

Long term fix: add a logout on our dashboard so we can switch users correctly

**Comment by ratnakar-asara** [comment]
Unfortunately the problem doesn't stop there.
When switched to different browser I could see the Starter Network is not functional any more from the Browser.Even after deletion of the existing network and re-create a new one.

![wrong_indication](https://cloud.githubusercontent.com/assets/18034452/17971175/a9589636-6aa7-11e6-9a50-84025a78b185.png)

![blockchain_dash](https://cloud.githubusercontent.com/assets/18034452/17971193/bf5e7ac2-6aa7-11e6-953a-7210bf6d9e2d.png)

![demo_chaincode](https://cloud.githubusercontent.com/assets/18034452/17971197/c2b476a4-6aa7-11e6-9222-160e1fae83ca.png)

However, when I try to get the height after deploying chaincode example02 from PostMan, I could see response from peers (Though deploy fails which is a different issue). This gives a wrong indication in UI that peers are stopped, Also dashboard is not functional anymore.

![heights](https://cloud.githubusercontent.com/assets/18034452/17971169/a17b7528-6aa7-11e6-9f7e-a9894a09d2f3.png)

**Comment by bmos299** [comment]
@dshuffma-ibm do we think this is a browser issue or the service?  Can we either document the different behaviors or investigate fixing them? What do you think?  IGF also hit a browser issuer where peer status was incorrect and using a different browser addressed the issue.  Here is Min's statement: 

> ymchee [1:13 PM] 
>  Interesting—yes, it looks like it must be browser-related…looking back, I didn't restart my browser (was using Safari), but when I visit the dashboard…back, I didn't restart my browser (was using Safari), but when I visit the dashboard with a different browser (Firefox, actually) it looks ok...

**Comment by dshuffma-ibm** [comment]
@bmos299  I'm not sure what more documentation I can add other than what I wrote already.

_Short term fix is: don't do this. close your browser or use differently browsers when switching IBM ID users._
_Long term fix: add a logout on our dashboard so we can switch users correctly_

As is the code will not support having users flip through different IBM IDs.

---

As far as the IGF issue, that was differently entirely. When in doubt F5 your browser. There is too little information to try to "document" what went wrong there. Sounded like the error was between the keyboard and seat to me.

**Comment by mrshah-at-work** [comment]
Closing this issue, the solution is mentioned above.
