### ISSUE TITLE
Settingup Hyperledger Fabric Development Environment

### ISSUE THREAD

**Issue by shireesh18** [IBM-Blockchain/ibm-blockchain-issues#28]
Am following this link https://github.com/hyperledger/fabric to set up development environment on my machine. I am using Vagrant and Oracle virtual box to deploy the fabric code onto the virtual machine(ubuntu) . I could able to clone the code from the gerrit repository and bring up the virual box but the code has not been deployed or build on the virtual machine. It keeps giving me the below error.
How can I update protobuf on ubuntu, does the update still help ? I have read somewhere that even the latest protobuf version supports only proto2. Plz help to overcome this issue

==> default: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
==> default: make: **\* [vendor/github.com/golang/protobuf/jsonpb/jsonpb_test_proto/more_test_objects.pb.go] Error 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by mastersingh24** [comment]
@shireesh18  - the best place to get help for this particular issue is going to be via the #fabric-dev-env channel on the Hyperledger Slack.  You can request an invite here:    https://slack.hyperledger.org/

In the meantime, you might want to pull the latest code from Gerrit (or you should be able to clone the Github mirror you were using) and try again.   FYI - you can also use http://hyperledger-fabric.readthedocs.io/en/latest/dev-setup/devenv/   as an easy method to access the docs
