### ISSUE TITLE
Ledger not found issue with 'learn chaincode example'

### ISSUE THREAD

**Issue by bravera** [IBM-Blockchain/ibm-blockchain-issues#30]
I have tried several times now to run the 'learn chaincode example' and everything works fine up to the point when i try and execute my third transaction against the /chaincode API.

It doesnt matter if I try to run an Invoke or a Query, I always get the following error:

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for c9b0146abbeab6d24b97edfd313cf6c7c28343c7b53f5b8e53d735148d5d6a2ee32f16eb385f736ece027e3e7008f2a08bb41f02c5a34b4658d95ad825631ec8 - LedgerError - ResourceNotFound: ledger: resource not found)"
  },
  "id": 3
}

Any ideas?

**Comment by bravera** [comment]
I think this was user error. I had not noticed that I didnt have enough peers running to achieve consensus.  
Would be nicer for the user if the error message helped identity this though.....my experience was that the deploy seemed to complete successfully. It was only on the later transaction that an error was thrown, and then it did not highlight the lack of validating peers as being the issue.

**Comment by dshuffma-ibm** [comment]
thanks, good feedback. that's something we could add.

**Comment by bravera** [comment]
Do you have a backlog somewhere where I could add the story for this? I would be happy to do so

**Comment by dshuffma-ibm** [comment]
no worries, I've already added this to our developer issues.

**Comment by joshhus** [comment]
Could a pending consensus failure be pre-empted or broadcast before transactions are submitted; i.e. good to avoid many (or even one) users all submitting doomed transactions. Large networks I presume would have failover nodes so this never happens. ... And/or is there a queue where transactions are pending / re-submitted automatically after the consensus fix, so user doesn't have to re-submit them.
