### ISSUE TITLE
Issue in Query - read([ abc]) of chaincode investigator

### ISSUE THREAD

**Issue by ashish9308** [IBM-Blockchain/ibm-blockchain-issues#33]
I'm using chaincode-investigator to ensure the scope of testing in blockchain application and just following the marbles example which you explained by using my own instance I'm able to deploy the Chaincode Investigator Application in my machine and But When sending **value abc** to **Query - read([ abc])** , Getting an error like :
Error - read {
"readyState": 0,
"responseText": "",
"status": 0,
"statusText": "error"
}

Please send me the resolution.

**Comment by dshuffma-ibm** [comment]
lets solve this back in the other repo https://github.com/IBM-Blockchain/chaincode-investigator/issues/1
