### ISSUE TITLE
[GVT] Garbage characters in the Logs of the launched Blockchain service.

### ISSUE THREAD

**Issue by wangshsh** [IBM-Blockchain/ibm-blockchain-issues#34]
https://console.eu-gb.bluemix.net/

Steps:
Login https://console.eu-gb.bluemix.net/ with Bluemix id
Go to https://dev-console.stage1.ng.bluemix.net/catalog/services/blockchain/
Click Create button
Click to open the created service
Click Launch link
Click Logs tab
Click Logs next to Membership Services

Expected Result
All characters should be display correctly in the Logs.

CC: @seanbarclay @markelloggs 

will attach defect screenshot later, thanks~

**Comment by wangshsh** [comment]
will upload defect screenshot later

**Comment by mrshah-at-work** [comment]
Are you talking about something similar to following logs:

```
OUT - TRACE: 2016/09/12 04:05:28 ca.go:469: Reading certificate for hash �X��*�N$�-���Q�8�������w��F�+.
OUT - TRACE: 2016/09/12 04:05:28 eca.go:429: gRPC ECAP:ReadCertificateByHash
OUT - TRACE: 2016/09/12 04:05:28 ca.go:469: Reading certificate for hash �X��*�N$�-���Q�8�������w��F�+.
OUT - TRACE: 2016/09/12 04:05:28 eca.go:429: gRPC ECAP:ReadCertificateByHash
```

The Membership Services logs have some characters in the hash which are binary (not utf-8) thus they look like garbage characters.
