### ISSUE TITLE
Problems with VPs in lab2

### ISSUE THREAD

**Issue by AdrianClv** [IBM-Blockchain/ibm-blockchain-issues#40]
Hi,

I'm trying to follow the instructions in the PDF of the second lab but the Validating Peers' Status is always "Stopped". I've tried to restart them/relaunch the service, but it remains the same.

Here is an image:
![ibm-error](https://cloud.githubusercontent.com/assets/9255560/18725012/e87a819c-803e-11e6-8e86-a17c148b8bd0.PNG)

If I go to the next tab "Blockchain", all stats are set to 0 and it says "error: could not get chainstats".

**Comment by mrshah-at-work** [comment]
Hi @AdrianClv, can you mention the browser and the OS that you are using? We have seen this happening with some Browsers and OSs.

Also, can you please refresh the page and check if you still see the issue?
Sometimes, it takes time to get the response and the page times out.

Let us know if you still see the issue. Thanks.

**Comment by AdrianClv** [comment]
@mrshah-at-ibm I'm using Windows 10 + Firefox.
After refreshing the page It's still the same.

Update: I tried in Chrome and it works.

**Comment by dshuffma-ibm** [comment]
what version of firefox? could you go to Help -> About Firefox.

 `45.3.0` seems good
`49.0.x` seems good

maybe its an add-on you have?

**Comment by AdrianClv** [comment]
@dshuffma-ibm I'm using the version 49.0.
In 30 min or so i will check if the extensions have something to do.

Update:
I finally found the problem. I had to go to the address bar and in "Tracking protection", click on "Disable protection for this session". Now everything works fine. Thanks!

**Comment by dshuffma-ibm** [comment]
thanks for the update
