### ISSUE TITLE
Query failure

### ISSUE THREAD

**Issue by fu-nakayama** [IBM-Blockchain/ibm-blockchain-issues#41]
I had gotten the following error when I call query functions.
What does this error mean? What should I do to fix the issue?

Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for beada488d8e46fb82807ba089c3e036e7b6998191748ea6849b87e12fd1c3e200c4610449531a70ba7948d46f6458464ae9fcce41fc7f817482546a34d581cd1 - LedgerError - ResourceNotFound: ledger: resource not found)

Best Regards,
Fumio

**Comment by mrshah-at-work** [comment]
It means that the deployment was not successful.
1. Check if your chaincode compiles.
2. If you are deploying on bluemix, the chaincode is taking about 5 minutes to deploy.
3. Redeploy the chaincode.

Let us know if this helps.

**Comment by fu-nakayama** [comment]
Only query functions don't work on bluemix. invoke functions seem fine.
And If I wait 30 min, the error still occurred on query function.

**Comment by fu-nakayama** [comment]
Here is the code fragments.

var Ibc1 = require("ibm-blockchain-js"); 
var ibc = new Ibc1(); 
var chaincode = null;

ibc.load (opt, function (err, cc) {
    if (err != null) { 
        if (!process.error) process.error = { 
            type: "load", 
            msg: err.details 
        };
    } else { 
        chaincode = cc; 
        if (!cc.details.deployed_name || cc.details.deployed_name === "") { 
            //yes, go deploy 
            cc.deploy("init", [], null, cb_deployed); 
            console.log("deployed chaincode: ", cc.details.deployed_name); 
        } else { 
            console.log("chaincode summary file indicates chaincode has been previously deployed", cc.details.deployed_name); 
        } 

```
    function cb_deployed(){ 
            console.log("sdk has deployed code and waited"); 
    } 
} 
```

});

app.post("/invoke/issue", function(req, res) {
    // invoke.issue
    var param = {};
    param = req.body;
    chaincode.invoke.issue([
        JSON.stringify(param.projectId),
        JSON.stringify(param.issueAmount)
        ], cb_invoked);
    res.json(param);

```
function cb_invoked(e, a) {
    console.log("response invoke.issue: ", e, a);
}
```

});

app.get("/project/:id", function(req, res) {
    if (!chaincode) {
        res.sendStataus(500);
    } else {
        chaincode.query.get_project([req.params.id], function(err, result) {
            if (err) {
                res.sendStatus(500);
            } else {
                res.send(JSON.parse(result));
            }
        });
    }
});

**Comment by fu-nakayama** [comment]
I think there is some trouble on blockchain on bluemix.
invoke function could be error, but my code didn't detect the error.
Now blockchain service seems in trouble.
I'll try recreate the service tomorrow.

**Comment by mrshah-at-work** [comment]
The deploy & invoke functions return fine (200), indicating that the transaction was submitted successfully. The transaction might not be successfully executed.

Thus, you should check on the status of the transaction ID to check if the transaction was committed successfully.

**Comment by fu-nakayama** [comment]
It was a environmental issue. Last night something was wrong on the environment.

**Comment by fu-nakayama** [comment]
It was environmental issue. After recreating the service, the issue was gone.
