### ISSUE TITLE
PutState failed immediately  after GetState

### ISSUE THREAD

**Issue by fu-nakayama** [IBM-Blockchain/ibm-blockchain-issues#43]
Hello I have a question about "Transaction execution failed."

Here is my code.
https://github.com/fu-nakayama/InvestEffect/blob/master/OpeEx1.go

When I called invoke.confirm, I got the following error.
How can I resolve the error?

ERR - 11:28:24.330 [shim] DEBU : [5a46451a]Received message TRANSACTION from shim
ERR - 11:28:24.330 [shim] DEBU : [5a46451a]Handling ChaincodeMessage of type: TRANSACTION(state:ready)
ERR - 11:28:24.330 [shim] DEBU : [5a46451a]Received TRANSACTION, invoking transaction on chaincode(Src:ready, Dst:transaction)
OUT - Entering into Invoke: confirm
ERR - 11:28:24.330 [shim] DEBU : [5a46451a]Sending GET_STATE
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]Received message RESPONSE from shim
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]Handling ChaincodeMessage of type: RESPONSE(state:transaction)
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]before send
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]after send
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]Received RESPONSE, communicated (state:transaction)
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]GetState received payload RESPONSE
ERR - 11:28:24.331 [shim] ERRO : [5a46451a]Transaction execution failed. Sending ERROR
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]Move state message ERROR
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]Handling ChaincodeMessage of type: ERROR(state:transaction)
ERR - 11:28:24.331 [shim] DEBU : [5a46451a]send state message ERROR

**Comment by fu-nakayama** [comment]
The things I want to do on the code is:
1. get the current data by GetState
2. update the data
3. put the new data by PutState

Is it acceptable code in a function of invoke?
Should GetState be called in Query and PutState be called in Invoke?

Regards,
Fumio

**Comment by masterDev1985** [comment]
I haven't had a chance to try your chaincode out myself, but I would recommend adding a few more debug statements to pinpoint the error you are seeing.  In the response to the invoke, which of the errors in your chaincode are being returned?

To your second post, that is exactly the sort of thing you want to do in an invoke.  Queries should only be calling GetState, and I believe you will trigger an error if you try to call PutState inside a query, as queries are not supposed to make changes to the state.  Invokes can call both.

**Comment by fu-nakayama** [comment]
I added some debug message as the following.

if function == "confirm" {      // project //
        fmt.Println("Entering into confirm")
        // issue (ProjectId, Entity)
        if len(args) != 2 {
            return nil, errors.New("##### OpeEx1: Incorrect number of arguments. Expecting 2 arguments for confirm #####")
        }

```
    // Get the state from the ledger
    var project_record Project
    project_id := args[0]
    project_key := args[0] + "project"

    fmt.Println("Calling GetState in confirm")
    project_asbytes, err := stub.GetState(project_key)
    if err != nil {
        return nil, errors.New("##### OpeEx1: Failed to get state for project_id: " + project_id + " #####")
    }

    fmt.Println("Calling Unmarshal in confirm")
    if err = json.Unmarshal(project_asbytes, &project_record) ; err != nil {
        return nil, errors.New("##### OpeEx1: Error unmarshalling data " + string(project_asbytes) + " #####")
    }
    fmt.Printf("Invoke (confirm): project_id = %s\n",   project_id)
    fmt.Printf("Invoke (confirm): project_name = %s\n", project_record.ProjectName)
```

.....

Then, I got the following log.

OUT - Entering into confirm
OUT - Calling GetState in confirm
ERR - 01:44:45.124 [shim] DEBU : [8846cba4]Sending GET_STATE
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]Received message RESPONSE from shim
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]Handling ChaincodeMessage of type: RESPONSE(state:transaction)
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]before send
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]after send
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]Received RESPONSE, communicated (state:transaction)
OUT - Calling Unmarshal in confirm
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]GetState received payload RESPONSE
ERR - 01:44:45.125 [shim] ERRO : [8846cba4]Transaction execution failed. Sending ERROR
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]Move state message ERROR
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]Handling ChaincodeMessage of type: ERROR(state:transaction)
ERR - 01:44:45.125 [shim] DEBU : [8846cba4]send state message ERROR

So, it seems the error occurred at calling Unmarshal?
What should I do for next?

Regards,

**Comment by fu-nakayama** [comment]
It was my mistake that the key was wrong. So, the GetState could be failed.
