### ISSUE TITLE
Validating peers randomly stopping with car leasing demo

### ISSUE THREAD

**Issue by bravera** [IBM-Blockchain/ibm-blockchain-issues#46]
I tried to use an existing instance of the car leasing demo today but VP0 kept on randomly stopping.
I trashed the whole things and deployed a new version, but now multiple peers are randomly stopping before the demo has even initialised itself.
I try to restart them and they appear to, but then shortly stop again

**Comment by mrshah-at-work** [comment]
Thanks @bravera. Can you give us the network ID (on the top right corner of the dashboard), so we can have a look?

The status of the peers is returned by the API call to `/chain` endpoint. Sometimes the status shows stopped because the API call might have timed out. Can you try the chain endpoint manually and see if it responds (you can go to https://<network_id>_vp0.us.blockchain.ibm.com/chain for vp0 in a browser)?

**Comment by bravera** [comment]
The above was reported on US South. I have now tried a couple of times on UK too and here the VPs seem to stay up more consistently but the demo never seems to get beyond the 'just finalizing set up' message.
The network ID on US South is 39ca0462-3b5b-4036-860d-b7532d05a911
On Uk it is 14c15cc1-9ad3-4055-94d7-722491ee79ec
Calling the /chain endpoint returns a 503

**Comment by mrshah-at-work** [comment]
Thanks for sharing the network IDs

I went through the configuration.

Can you check now?
https://39ca0462-3b5b-4036-860d-b7532d05a911_vp0.us.blockchain.ibm.com/chain
https://39ca0462-3b5b-4036-860d-b7532d05a911_vp1.us.blockchain.ibm.com/chain
https://39ca0462-3b5b-4036-860d-b7532d05a911_vp2.us.blockchain.ibm.com/chain
https://39ca0462-3b5b-4036-860d-b7532d05a911_vp3.us.blockchain.ibm.com/chain

https://14c15cc1-9ad3-4055-94d7-722491ee79ec_vp0.us.blockchain.ibm.com/chain
https://14c15cc1-9ad3-4055-94d7-722491ee79ec_vp1.us.blockchain.ibm.com/chain
https://14c15cc1-9ad3-4055-94d7-722491ee79ec_vp2.us.blockchain.ibm.com/chain
https://14c15cc1-9ad3-4055-94d7-722491ee79ec_vp3.us.blockchain.ibm.com/chain

**Comment by bravera** [comment]
UK instance seems fine now, but the US one still has a problem with VP2

**Comment by dshuffma-ibm** [comment]
@bravera when you say that peers are stopping, how do you know?  are you referring to the bluemix dashboard or peer logs or some other means?

**Comment by bravera** [comment]
Yes - VP2 is showing as stopped in the bluemix dashboard and calling the /chain endpoint on it confirms it is not running.
Today I have deployed a new version of Commercial Paper demo on UK and it is also struggling with membership services and VPs stopping.

**Comment by dshuffma-ibm** [comment]
Thanks for the info. We have also noticed networking issues. The team is working on a fix.

**Comment by dhyey20** [comment]
We have fixed some of these issues in the new version that we launched in 10-Nov. Please try the new version.
