### ISSUE TITLE
new chaincode docker images/container created but failed to start

### ISSUE THREAD

**Issue by git123456** [IBM-Blockchain/ibm-blockchain-issues#47]
This is on Mac, Fabric v0.5.

This is what is showing in the peer log when tried to deploy a new chaincode:
**[31m19:19:32.719 [dockercontroller] Start -> ERRO 071[0m start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}**

This is running one node peer in, turn off security.

Docker version :
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by mrshah-at-work** [comment]
Starting docker version 1.12, the docker start API does not support hostConfig.

With fabric v0.5, you will have to use docker version 1.11 or lower.

**Comment by git123456** [comment]
First of all it was not stated in the doc, second of all v1.11 have to same error.

I switched fabric 0.6 and it just works (no change in docker version).  Don't think 0.5 is stable at all.

**Comment by mrshah-at-work** [comment]
With docker 1.11 on the server, it should show as a warning and not an error. Thus, it will not be breaking.

I have not seen many issues with 0.5, except for a state-transfer issue.
