### ISSUE TITLE
blockchain validating peer is not running after launch.

### ISSUE THREAD

**Issue by saemy331** [IBM-Blockchain/ibm-blockchain-issues#5]
After I click the launch button, network tab shows five servers.
membership server is running properly but 4 validating peers not running.
I tried network reset, restart each VP server but none is helping.

my blockchain is v2 as below.
https://obc-service-broker-prod.mybluemix.net/v2/monitor/XXXXXXXX

**Comment by mastersingh24** [comment]
@saemy331  - can you send me your network id (it's in the top right corner of the dashboard).  You can either post it here or you can send email me direct (  gari.r.singh@gmail.com )

**Comment by mastersingh24** [comment]
Closing as this should now be fixed
