### ISSUE TITLE
Calling APIs from C#

### ISSUE THREAD

**Issue by mslangford** [IBM-Blockchain/ibm-blockchain-issues#50]
Hi,
I just wanted to call out that we ran into an issue calling the APIs from C# when using object serialization to create the JSON. "Params" is part of the API spec but is also a reserved word in C#, so cannot be used in the JSON object structure. We got around it by doing a string replace, but just thought I'd mention it.

Thanks
Matt

**Comment by dshuffma-ibm** [comment]
thanks for the heads up.  unfortunately the HTTP API spec is going to be retired at some unknown date in the future. at which point you would have to switch over to the gRPC APIs.  

node.js sdk using gRPC - [Hyperledger Fabric Client](https://www.npmjs.com/package/hfc)
general docs - [Hyperledger Fabric Protocol](http://hyperledger-fabric.readthedocs.io/en/latest/protocol-spec/)

**Comment by ghost** [comment]
Maybe this helps

http://www.grpc.io/docs/tutorials/basic/csharp.html

**Comment by mastersingh24** [comment]
thanks for the info on C#.  Duly noted for any future APIs.  Closing as we are not making any changes to the v0.6 version of the underlying Hyperledger Fabric
