### ISSUE TITLE
Showing 6 peers when deployed the same chaincode twice

### ISSUE THREAD

**Issue by ratnakar-asara** [IBM-Blockchain/ibm-blockchain-issues#53]
Deployed the same chaincode (chaincode_examplo02) twice using **NODE_SDK**.
Could see 6 peers in Dashboard

![pasted image at 2016_10_06 12_19 pm](https://cloud.githubusercontent.com/assets/18034452/19161170/b6d4fa5e-8bc0-11e6-9440-e830fa215d57.png)

**Comment by mrshah-at-work** [comment]
Thanks for reporting this. This might be a bug as I checked and found 6 containers for the chaincode. 3 are running & 3 are in Created state.

We will look into this, if you want, I can manually remove the containers in `Created` state for now.

**Comment by mastersingh24** [comment]
I don't think we can reproduce this any longer with the updated BMX starter networks
