### ISSUE TITLE
Calling blockchain API using SOAPUI java.lang.IllegalArgumentException: Name must not be NULL

### ISSUE THREAD

**Issue by tcnt** [IBM-Blockchain/ibm-blockchain-issues#54]
When I try to call network/peers api using vp0 node in bluemix I get the following error in SoapUI.
java.lang.IllegalArgumentException: Name must not be NULL
Calling the same in Postman is no problem. Also using the url in a browser works fine.
Calling the API using my local hyperledger on the Mac also is no problem using Soapui since the local url does not contain an underscore.

From what I understand the use of an _ (Underscore) in the hostname of the url is not according to the rules. Apparently SoapUI can not handle this but also my middleware tool I wanted to use to connect can not handle it.
The url I use for API call is for example ending in: _vp0.us.blockchain.ibm.com:443/network/peers.
Is there any way to get around this or is it possible somehow to change the urls in the bluemix service?

**Comment by mastersingh24** [comment]
Unfortunately some tools have decided to strictly enforce hostname naming conventions.  I am not sure there is anything you can do now, but we are updating the naming convention in an upcoming release to replace the '_' with '-'
