### ISSUE TITLE
CP demo : Failed to enroll WebAppAdmin member ---> Error: Identity or token does not match

### ISSUE THREAD

**Issue by gitjps** [IBM-Blockchain/ibm-blockchain-issues#56]
I created the Commercial Paper Demo app (http://www.ibm.com/blockchain/for_developers.html).
Initially it worked, but now it keeps crashing after start.

https://github.com/IBM-Blockchain/cp-web?cm_mc_uid=83173706584114692626941&cm_mc_sid_50200000=1476555087#readme

Failed to enroll WebAppAdmin member  ---> Error: Identity or token does not match

https://github.com/diegomasini/hyperledger-fabric/tree/master/sdk/node

**Comment by masterDev1985** [comment]
See #51.
