### ISSUE TITLE
For IBM Blockchain on Bluemix which shim works?

### ISSUE THREAD

**Issue by TarantulaTechnology** [IBM-Blockchain/ibm-blockchain-issues#57]
Which should be used for the currently deployed IBM Blockchain on Bluemix: 1 or 2? 
1. shim.ChaincodeStub
2. shim.ChaincodeStubInterface

marksmacbookpro:finished markmorris$ go build ./
# github.com/TarantulaTechnology/learn-chaincode/finished

./chaincode_finished.go:22: cannot use new(SimpleChaincode) (type _SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
        *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
                have Init(_shim.ChaincodeStub, string, []string) ([]byte, error)
                want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

**Comment by tcnt** [comment]
Bluemix is still using hyperledger v0.5 which is using the first option. When you want to compile it locally make sure to use the correct hyperledger version on your local machine.
See also https://github.com/IBM-Blockchain/ibm-blockchain-issues/issues/29

**Comment by masterDev1985** [comment]
Thanks, @tcnt !
