### ISSUE TITLE
Cannot start validating peers

### ISSUE THREAD

**Issue by pongnumkul** [IBM-Blockchain/ibm-blockchain-issues#59]
I started a blockchain project on ibm blockchain, but haven't been able to get the validating peers to run. The Network ID is 7010c56459ec453d8609dfe889e7be1a.  The membership services peer is running, as the attached picture shows:

![image](https://cloud.githubusercontent.com/assets/22909277/19504544/50cefaa0-95e5-11e6-85f5-b9cbddfed824.png)

I'm attaching the log of validating peer 0 here:
[logs.txt](https://github.com/IBM-Blockchain/ibm-blockchain-issues/files/537880/logs.txt)

Please advice on how to resolve the issue. Thank you.

**Comment by sadiquehannure** [comment]
facing same problem, my network id 27fb0d02a6144e8c83659402a17820baIBM

**Comment by mrshah-at-work** [comment]
Hi @suporn8 & @sadiquehannure, I just checked your UI and it looks good. Can you please check again?

**Comment by sadiquehannure** [comment]
Then why I am not able to start any of the peer? They are in "stopped" state. 

When I go to "Demo Chaincode", all the "deploy" buttons are disabled.  
- -
  BRs,
  Sadique

**Comment by mrshah-at-work** [comment]
@sadiquehannure looks like this has something to do with the browser and security. Can you try using a different web browser?

**Comment by sadiquehannure** [comment]
How it related to browser? because Membership Services is running showing & showing correctly. 

I tried with Chrome & Microsoft IE but same result. All peers are stopped one

**Comment by mrshah-at-work** [comment]
Can you tell us what version of chrome are you running (Settings->Help->About Chrome)?

This is what I see on Chrome:

![image](https://cloud.githubusercontent.com/assets/15948008/19515569/01a11216-95c6-11e6-9285-bf9f8e737e0c.png)

**Comment by sadiquehannure** [comment]
![network](https://cloud.githubusercontent.com/assets/18302962/19515764/6d476772-9616-11e6-906d-3d0f11e7dd45.png)
![demo_chaincode](https://cloud.githubusercontent.com/assets/18302962/19515770/766a439c-9616-11e6-8b84-f3708d52b4da.png)

Version 53.0.2785.143 m

**Comment by masterDev1985** [comment]
@sadiquehannure Could you open up Chrome's developer tools and watch the Console when you load this page?  I'd like to see what error is coming back on the requests your browser is making to determine whether a peer is up or not.

**Comment by dshuffma-ibm** [comment]
in addition to @masterDev1985's suggestion try opening this link directly in your browser:
https://7010c56459ec453d8609dfe889e7be1a-vp0.us.blockchain.ibm.com:444/chain

If you cannot reach it, you may have some strange firewall setting preventing your browser from reaching the peers.

**Comment by sadiquehannure** [comment]
You are right, its firewall issue. Thanks for help
- -
  BRs,
  Sadique
