### ISSUE TITLE
blockchain validating peer is not running 

### ISSUE THREAD

**Issue by gunvant** [IBM-Blockchain/ibm-blockchain-issues#6]
I have tried to deploy marble sample blockchain  app but all the validating peer is not running. I have also reset network but the issue is not resolve. It seems the current release is not stable.

I never faced this kind of issue in previous release.

Please resolve it ASAP

**Comment by mastersingh24** [comment]
can you post part of your logs or the error you are seeing?

**Comment by wissamdagher** [comment]
Hello I'm also getting the same error, below is a part of the log of one of the peers
/enrollment.id]...
ERR - [36m16:53:24.700 [crypto] loadEnrollmentID -> DEBU 025[0m [validator.peer0] Setting enrollment id to [peer0].
ERR - [36m16:53:24.701 [crypto] loadEnrollmentChainKey -> DEBU 026[0m [validator.peer0]  Loading enrollment chain key...
ERR - [36m16:53:24.701 [crypto] loadPrivateKey -> DEBU 027[0m [validator.peer0] Loading private key [chain.key] at [/var/hyperledger/production/crypto/validator/peer0/ks/raw/chain.key]...
ERR - [36m16:53:24.701 [crypto] loadTLSCACertsChain -> DEBU 028[0m [validator.peer0]  Loading TLSCA certificates chain...
ERR - [36m16:53:24.701 [crypto] loadExternalCert -> DEBU 029[0m [validator.peer0] Loading external certificate at [/certs/DigiCertCA.crt]...
ERR - [36m16:53:24.701 [crypto] loadTLSCACertsChain -> DEBU 02a[0m [validator.peer0]  Loading TLSCA certificates chain...done
ERR - [36m16:53:24.701 [crypto] loadTLSCertificate -> DEBU 02b[0m [validator.peer0]  Loading tls certificate...
ERR - [36m16:53:24.701 [crypto] loadCertX509AndDer -> DEBU 02c[0m [validator.peer0] Loading certificate [tls.cert] at [/var/hyperledger/production/crypto/validator/peer0/ks/raw/tls.cert]...
ERR - [31m16:53:24.701 [crypto] loadCertX509AndDer -> ERRO 02d[0m [validator.peer0] Failed loading certificate [tls.cert]: [open /var/hyperledger/production/crypto/validator/peer0/ks/raw/tls.cert: no such file or directory].
ERR - [31m16:53:24.701 [crypto] loadTLSCertificate -> ERRO 02e[0m [validator.peer0] Failed parsing tls certificate [open /var/hyperledger/production/crypto/validator/peer0/ks/raw/tls.cert: no such file or directory].
ERR - [31m16:53:24.701 [crypto] init -> ERRO 02f[0m [validator.peer0] Failed initiliazing crypto engine [open /var/hyperledger/production/crypto/validator/peer0/ks/raw/tls.cert: no such file or directory].
ERR - [31m16:53:24.701 [crypto] func1 -> ERRO 030[0m Failed validator initialization [peer0]: [open /var/hyperledger/production/crypto/validator/peer0/ks/raw/tls.cert: no such file or directory]

**Comment by AffineR** [comment]
Did you delete everyone's work when  you upgraded the fabric? 

We can't access our blockchains from April we have been using for demo purposes. How do we get them back?

We are logging on and getting "blockchain not found 404"

I want to know:

1. Was our work of months deleted without any notice or our authority?

2. If so, who did that? 

3. Who in Armonk can fix this?

NOW

**Comment by dshuffma-ibm** [comment]
@AffineR i've replied in a [relevant issue](https://github.com/IBM-Blockchain/ibm-blockchain-issues/issues/75)
