### ISSUE TITLE
Membership services down

### ISSUE THREAD

**Issue by arner** [IBM-Blockchain/ibm-blockchain-issues#60]
Hi, in two different organizations and with different services I can't access my membership services. They show up as 'loading' in the network tab and when I try to view the logs I get 502 Bad Gateway: Registered endpoint failed to handle the request.

**Comment by mrshah-at-work** [comment]
@arner Can you post your network id here so we can have a look?

**Comment by arner** [comment]
71c6b894-ea43-4650-abea-fecab2b039c3 
and
f7f68ea4-8c7e-44b6-bc32-1d827fd6cb08

**Comment by mrshah-at-work** [comment]
@arner can you go ahead and create a new service & let us know if you still see the same issue?

Thanks.

**Comment by arner** [comment]
That works, thanks.

**Comment by arner** [comment]
Hi, it happened again. It may have something to do with me connecting to the memberservice from my own laptop using the hfc client. 

If you have access to the logs (I can't see them from the dashboard) it might be worth looking at. Even if I did something wrong it's still an issue because it goes down and can't even be restarted to bring up again. Network id: 320155f047b94c8b8bee26e7c689bcdc. I'll keep it running for now.

EDIT: it came back up last night.
