### ISSUE TITLE
Unicode characters not properly displayed in Blockchain dashboard

### ISSUE THREAD

**Issue by steveatkin** [IBM-Blockchain/ibm-blockchain-issues#61]
Unicode characters are not being properly displayed in the Blockchain dashboard. I have verified that chaincode can properly store and retrieve Unicode data, but the dashboard does not properly display Unicode characters. Here is the character sequence that I used 上海 and in the dashboard these characters are mangled. See attached screenshot.
<img width="634" alt="screen shot 2016-10-20 at 8 57 00 am" src="https://cloud.githubusercontent.com/assets/5531596/19560784/d04b8e42-96a3-11e6-9c4f-c132fc20ddcd.png">

**Comment by dshuffma-ibm** [comment]
thanks, we'll take a look at this

**Comment by steveatkin** [comment]
What is the reason for marking this as wontfix? Do you plan to address this in a later release rather than fixing this in the current codebase?

**Comment by dshuffma-ibm** [comment]
the starter plan no longer exists.
