### ISSUE TITLE
What is the current version of fabric inside Bluemix?

### ISSUE THREAD

**Issue by MrBuggySan** [IBM-Blockchain/ibm-blockchain-issues#62]
On the status page of the IBM blockchain service in Bluemix, it says Productionv0.4.3. Does this mean it corresponds to v0.4.3 fabric? I'm trying to use the HFC to register new users:
https://github.com/hyperledger/fabric/tree/master/sdk/node

I ask this because I am trying to run this example https://console.ng.bluemix.net/docs/services/blockchain/etn_sdk.html#nodesample

I'm getting 

```
Enrolled admin sucecssfully

Enrolled and registered JohnDoe successfully

Deploying chaincode ...
E1022 16:21:22.374341656   20082 frame_data.c:168]           Bad GRPC frame type 0x3c

Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"],"certificatePath":"/certs/blockchain-cert.pem","chaincodePath":"chaincode_example02"}, error={"error":{"code":2,"metadata":{"_internal_repr":{}}},"msg":"Error"}

```

I'm thinking this is so because of the wrong version of HFC used?

**Comment by mastersingh24** [comment]
@MrBuggySan  - what OS are you running on?   We've seen this error occasionally when using certain releases of the grpc package (used by hfc).   I think we have updated this in the latest hfc releases for both v0.5 and v0.6.

I think the directions in the doc you reference say to use `hfc@0.5.3`.  I'd recommend moving to **`hfc@0.5.4`**

**Comment by MrBuggySan** [comment]
Hi @mastersingh24 I am using Ubunti 16.04.
I upgraded to hfc@0.5.4 and this the terminal output:

```
-----------------------------------------------------------


/home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/helloblockchain.js:145
        if (err) throw Error("\nERROR: failed to enroll admin : %s", err);
                 ^

Error: 
ERROR: failed to enroll admin : %s
    at Error (native)
    at /home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/helloblockchain.js:145:24
    at /home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/node_modules/hfc/lib/hfc.js:468:28
    at /home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/node_modules/hfc/lib/hfc.js:718:24
    at Object.callback (/home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/node_modules/hfc/lib/hfc.js:1898:24)
    at /home/andreibuiza/SchoolCode/capstone/HFCSampleNodeJS/node_modules/grpc/src/node/src/client.js:420:14

```

Now I cannot register my admin. My service credentials are from the blockchain service of Bluemix so I'm sure the error is not because of that.

**Comment by MrBuggySan** [comment]
@mastersingh24 it works now! I made a new IBM blockchain service and it deployed, invoked, queried succesfully.
