### ISSUE TITLE
Problems starting Blockchain Validating Peers Aagain !!

### ISSUE THREAD

**Issue by chaitanyaamin** [IBM-Blockchain/ibm-blockchain-issues#63]
![screenshot from 2016-10-24 12 44 49](https://cloud.githubusercontent.com/assets/11228221/19636572/c0225b6c-99e7-11e6-8729-b6a60f38bcd3.png)
Hi

My Network Id is d9abdd2b2bb446859376e578edb73cb5

I deleted my previous Blockchain and created a brand new chain. Chain code for Marbles was uploaded. However the Validating Peers just dont start. 

I had filed a similar problem ticket last week. It got resolved by deleting the Blockchain service and reinstalling a new one. Could you please help as its becoming very very difficult to work with IBM Blockchain.

Chaitanya

**Comment by mastersingh24** [comment]
when I look at you network, I see that all of the peers are actually running

**Comment by masterDev1985** [comment]
@chaitanyaamin open the [developer tools](https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox) for your browser and watch the Console when loading this page.  I suspect the request that your browser is making to determine whether peers are up or not is being blocked.

**Comment by chaitanyaamin** [comment]
It started after I filed critical level ticket. I still have no clue what
was wrong and why it was not working
