### ISSUE TITLE
Problems running HFC@0.5.3 -- Secure handshake failure

### ISSUE THREAD

**Issue by paulwizviz** [IBM-Blockchain/ibm-blockchain-issues#68]
I have a nodejs app running on Bluemix connecting to an instance of Bluemix Blockchain High security network. I am using HFC@0.5.3.

   Everything I try to connect, I get a secure handshake failure with error 1.

   I have set the GRPC_SSL_CIPHER_SUITES according to https://github.com/grpc/grpc/blob/1a62ec83b7af9c4437164d10fa23197c64542382/doc/environment_variables.md. But it still did not work.

    Is this an issue with HFC or connectivity from Bluemix cloudfoundry node runtime?

**Comment by masterDev1985** [comment]
@paulwizviz Give `hfc@0.5.4` a try.  It has an updated grpc library which resolves some of these handshake issues.

**Comment by jonathan-yk-tan** [comment]
having the same issue, even when using hfc 0.5.4 , more on https://github.com/IBM-Blockchain/SDK-Demo/issues/3

**Comment by goupadhy** [comment]
we are following the demo https://github.com/IBM-Blockchain/SDK-Demo
we are using hfc@0.6.5 but still have this handshake issue. Not sure what is the issue

**Comment by masterDev1985** [comment]
@goupadhy the version of hfc you are using is correct.  Make sure you are using the latest Node.js LTS version (v6.9.2 at time of writing).  If you have a different version installed, uninstall it, and make sure to remove and global modules that have been installed by npm (see [here](http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally)).  After that, go back through the demo's instructions.  If that still doesn't work, comment on https://github.com/IBM-Blockchain/SDK-Demo/issues/3 so that the maintainers of the demo can see that people are still having problems.

**Comment by goupadhy** [comment]
tried the steps you told, but with no luck. I have updated Node.js LTS version 6.9.2. Yes i wil put a comment in there aswell.

**Comment by goupadhy** [comment]
------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://2aace0d55476405d9229d730a26ff8df-ca.us.blockchain.ibm.com:30003

Validating Peer0 : grpcs://2aace0d55476405d9229d730a26ff8df-vp3.us.blockchain.ibm.com:30003
Validating Peer1 : grpcs://2aace0d55476405d9229d730a26ff8df-vp1.us.blockchain.ibm.com:30003
Validating Peer2 : grpcs://2aace0d55476405d9229d730a26ff8df-vp0.us.blockchain.ibm.com:30003
Validating Peer3 : grpcs://2aace0d55476405d9229d730a26ff8df-vp2.us.blockchain.ibm.com:30003

Event Url on Peer0 : grpcs://2aace0d55476405d9229d730a26ff8df-vp3.us.blockchain.ibm.com:31003
Event Url on Peer1 : grpcs://2aace0d55476405d9229d730a26ff8df-vp1.us.blockchain.ibm.com:31003
Event Url on Peer2 : grpcs://2aace0d55476405d9229d730a26ff8df-vp0.us.blockchain.ibm.com:31003
Event Url on Peer3 : grpcs://2aace0d55476405d9229d730a26ff8df-vp2.us.blockchain.ibm.com:31003

-----------------------------------------------------------


Enrolled admin sucecssfully

Enrolled and registered JohnDoe successfully

Deploying chaincode ...
E1228 20:56:14.289642000 123145312870400 handshake.c:128] Security handshake failed: {"created":"@1482938774.289593000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1482938774.289586000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"],"chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"}, error={"error":{"code":14,"metadata":{"_internal_repr":{}}},"msg":"Error"}

**Comment by deepakjha14** [comment]
Hi, I am facing the same problem, I am using hfc@0.6.5, 

Deploying chaincode ...
E0313 19:24:51.893000000 12544 handshake.c:128] Security handshake failed: {"created":"@1489413291.893000000","description":"Handshake read failed","file":"..\src\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":[{"created":"@1489413291.893000000","description":"End of TCP stream","file":"..\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (D:\Personal-Projects\BlockChain\SDK-Demo\SDK-Demo\node_modules\grpc\src\node\src\client.js:189:19)
    at ClientDuplexStream._readsDone (D:\Personal-Projects\BlockChain\SDK-Demo\SDK-Demo\node_modules\grpc\src\node\src\client.js:158:8)
    at readCallback (D:\Personal-Projects\BlockChain\SDK-Demo\SDK-Demo\node_modules\grpc\src\node\src\client.js:217:12)


Any luck people???

**Comment by dshuffma-ibm** [comment]
HFC is not compatible with the supported releases of Fabric (v1.0.0, v1.0.1, v1.0.2).  use [Fabric Client](https://www.npmjs.com/package/fabric-client) instead.
