### ISSUE TITLE
The whole network is not running and hitting restart button doesn't start membership service and peers

### ISSUE THREAD

**Issue by frbrkoala** [IBM-Blockchain/ibm-blockchain-issues#7]
After recent outage Membership services and Validating peers are stopped and hitting restart button doesn't start them again.

**Comment by dshuffma-ibm** [comment]
Sounds like you have one of the new 4 peer networks created **after** 7/15.  If so it will not be working.  We have not re-enabled those networks yet and restart will have no effect.

You should see this message on your status tab:

![image](https://cloud.githubusercontent.com/assets/16085295/17213629/1f25fe6e-54a3-11e6-8a73-ab465c81c05b.png)


If you don't have one of our older networks on hand, I'm afraid you will have to hold off until we bring creation of new networks back online.

**Comment by frbrkoala** [comment]
Ok, that looks like this is my case and I need to wait then. Thanks for prompt response!
