### ISSUE TITLE
Blockchain service Dashboard looks to be down

### ISSUE THREAD

**Issue by zamrokk** [IBM-Blockchain/ibm-blockchain-issues#71]
Cannot access Dashboard of the service

![image](https://cloud.githubusercontent.com/assets/2536368/20359561/bbfc1bc6-ac30-11e6-8a25-f6ac2bb61249.png)

**Comment by jensfr** [comment]
I have the exact same problem

**Comment by dshuffma-ibm** [comment]
sorry about that, fixed. networks older than 11/10 were temporarily affected.
