### ISSUE TITLE
Reset Network Feature Missing 

### ISSUE THREAD

**Issue by jonathan-yk-tan** [IBM-Blockchain/ibm-blockchain-issues#72]
Since the upgrade to 0.6.1 and the new dashboard on Bluemix, the reset network function/button seems to be missing now. How can we reset the network similar to 0.5.3?

**Comment by mrshah-at-work** [comment]
@jonathan-yk-tan are you on HSBN or Starter network?

**Comment by dshuffma-ibm** [comment]
only HSBN networks will see a reset button.  Starter initially had a reset button back in July (v0.4.0) but was removed in August (v0.4.1). also the service version is currently v1.0.0.

**Comment by jonathan-yk-tan** [comment]
@mrshah-at-ibm I am currently using Starter , waiting for the approvals/access to HSBN for a customer. @dshuffma-ibm so there's no way to reset the network if I am using Starter now? We used to use this feature as part of the Proof-of-Technology / Development setup.

**Comment by mrshah-at-work** [comment]
@jonathan-yk-tan resetting a starter network is as simple as deleting the network and creating a new one.

**Comment by mastersingh24** [comment]
closing as this is working as designed and the answer is to delete and and then recreate when using the Starter plan
