### ISSUE TITLE
bluemix blockchain node.js exercise fails to enroll member JoneDoe1

### ISSUE THREAD

**Issue by KennethNagin** [IBM-Blockchain/ibm-blockchain-issues#74]
I'm following the bluemix blockchain exercise to to deploy a node.js block chain on https://console.ng.bluemix.net/docs/services/blockchain/etn_sdk.html.
However after Enrolling admin successfully it fails to enroll member JoneDoe1

> node helloblockchain.js
     ......
Enrolled admin sucecssfully
/home/nagin/work/src/github.com/SDK-Demo/helloblockchain.js:105
            if (err) throw Error(" Failed to register and enroll " + enrollName + ": " + err);
                     ^

Error:  Failed to register and enroll JohnDoe1: Error: Invalid affiliation group 00001
    at Error (native)
    at /home/nagin/work/src/github.com/SDK-Demo/helloblockchain.js:105:28
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:545:28
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:787:24
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:729:24
    at Object.callback (/home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:1988:24)
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/grpc/src/node/src/client.js:420:14

I installed hfc with npm install hfc@0.6.5
I also am git checkout v0.5 for the application.

What am I doing wrong?

--Ken

**Comment by javierpruedas** [comment]
Hello Ken,

I am having the same problem. Could you finally fix it?

**Comment by KennethNagin** [comment]
Unfortunately, no.  Infact the problem is worse since it can not enroll admin.  I've tried with both v0.5 and master, but both failed.  I also verified with DEBUG=hfc node helloblockchain.js that the correct admin credentials are being used.
Here is the trace:
$ DEBUG=hfc node helloblockchain.js

------------- ca-server, peers and event URL:PORT information: -------------

the network is listed correctly
-----------------------------------------------------------

  hfc Enrolling [req={"enrollmentID":"admin","enrollmentSecret":"6acda596c0"}] +0ms
  hfc [MemberServicesImpl.enroll] [{"enrollmentID":"admin","enrollmentSecret":"6acda596c0"}] +1ms
  hfc [MemberServicesImpl.enroll] Generating keys... +1ms
  hfc [MemberServicesImpl.enroll] Generating keys...done! +123ms
  hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d030107034200042d283be33c990717bd0344a81184f782ff316c15f597ee51591a13f6bd83d8d7220bd56fa379dd1c7a3d778f4691657247681dc530e1bd93e7a5013255da25ba" +3ms
  hfc [MemberServicesImpl.enroll] Adding signing key! +0ms
  hfc [MemberServicesImpl.enroll] Assding encryption key! +0ms
  hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1483280730,"high":0,"unsigned":false},"nanos":0},"id":{"id":"admin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[54,97,99,100,97,53,57,54,99,48]},"offset":0,"markedOffset":-1,"limit":10,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,45,40,59,227,60,153,7,23,189,3,68,168,17,132,247,130,255,49,108,21,245,151,238,81,89,26,19,246,189,131,216,215,34,11,213,111,163,121,221,28,122,61,119,143,70,145,101,114,71,104,29,197,48,225,189,147,231,165,1,50,85,218,37,186]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,168,199,89,167,241,54,240,144,133,227,199,196,7,146,168,245,46,180,47,46,35,128,171,128,216,42,100,110,176,249,54,34,46,97,32,77,93,16,185,1,68,134,236,192,119,157,119,193,107,32,54,6,203,96,141,198,49,210,120,196,191,179,204,55]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null}  +1ms
E0101 16:25:31.442499791   27921 handshake.c:128]            Security handshake failed: {"created":"@1483280731.442443861","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1483280731.442435215","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":948}]}
  hfc [MemberServicesImpl.enroll] failed to create cert pair: err={"code":14,"metadata":{"_internal_repr":{}}} +1s
  hfc [memberServices.enroll] err=Error, enrollment=undefined +1ms
/home/nagin/work/src/github.com/SDK-Demo/helloblockchain.js:135
        if (err) throw Error("\nERROR: failed to enroll admin : " + err);
                 ^

Error: 
ERROR: failed to enroll admin : Error
    at Error (native)
    at /home/nagin/work/src/github.com/SDK-Demo/helloblockchain.js:135:24
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:523:28
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:756:24
    at Object.callback (/home/nagin/work/src/github.com/SDK-Demo/node_modules/hfc/lib/hfc.js:2038:24)
    at /home/nagin/work/src/github.com/SDK-Demo/node_modules/grpc/src/node/src/client.js:420:14

**Comment by mrshah-at-work** [comment]
The same issue is being addressed at https://github.com/IBM-Blockchain/SDK-Demo/issues/13

**Comment by suffiasameera** [comment]
I'm facing the same problem. Any progress on how to go about resolving it? It's kind of urgent. 

Thanks :)

**Comment by mrshah-at-work** [comment]
@suffiasameera did you look at the link I mentioned in the comment above? I think that solved it for everyone commenting on this issue.

**Comment by dshuffma-ibm** [comment]
closed due to inactivity
