### ISSUE TITLE
Couldn't get attribute 'role'

### ISSUE THREAD

**Issue by khoazany** [IBM-Blockchain/ibm-blockchain-issues#77]
Hi there
 
I developed the chain code similar to the example seen in the link:
 
https://github.com/IBM-Blockchain/car-lease-demo/blob/master/Chaincode/src/vehicle_code/vehicles.go 
 
when I invoke my create_activity method:
 
{
"jsonrpc": "2.0",
"method": "invoke",
"params": {
"type": 1,
"chaincodeID":{
"name":"hdb-chaincode"
},
"ctorMsg": {
"Function": "create_activity",
"args":["a", "b", "c", "10"]
},
"secureContext": "admin",
"attributes": ["role","account"]
},
"id": 3
}

inside my invoke method I did the same thing as the example.

caller, caller_affiliation, err := t.get_caller_data(stub)

the get_caller_data get_username check_affiliation method which is exactly the same as the example.

this is the error
 
CREATE_ACTIVITY: Error retrieving caller information: Couldn't get attribute 'role'. Error: Failed retrieving extension.19:04:25.007 [shim] ERRO : [a121f55d]Transaction execution failed. Sending ERROR
 
which means that this method return error
 
func (t *SimpleChaincode) check_affiliation(stub shim.ChaincodeStubInterface) (string, error) {
affiliation, err := stub.ReadCertAttribute("role");
if err != nil { return "", errors.New("Couldn't get attribute 'role'. Error: " + err.Error()) }
return string(affiliation), nil

}

Just wonder what went wrong with the sample code given. Hope this provides an idea how we derive the error given.

Hope to hear you soon.

**Comment by cevou** [comment]
We had a similar issue. The problem was that the attribute authority was not enabled in the `membersrvc.yaml`. 
We found out by looking at this commit in the car lease demo: https://github.com/IBM-Blockchain/car-lease-demo/commit/2b7d8e72f5ab67291394213fb0ae08659736c35d#diff-ac1ea16993f7ac440990555df3f8928fR307 
The `enabled: true` is the only difference to the default `membersrvc.yaml`. After we changed it, everything worked fine.

**Comment by alachaitanya** [comment]
I changed it to `enabled: true` in `membersrvc.yaml` like you said. But it didn't solve the problem. 

"Error when querying chaincode: Error:Transaction or query returned with failure: QUERY: Error retrieving caller details: Couldn't get attribute 'role'. Error: Failed retrieving extension."

Did you do anything else besides this?

**Comment by vivekraut** [comment]
Any answer to the above question? I am also getting the same error. I am running it against the Bluemix blockchain service. What could be wrong?

**Comment by dshuffma-ibm** [comment]
this repo is mainly maintained by people that worked on the service (IBM Blockchain) and demos (marbles/cp-web).

if you have issues about your own hyperledger fabric, then check out [Jira](https://jira.hyperledger.org/secure/Dashboard.jspa)

**Comment by anrodon** [comment]
Anyone could give a solution to this?

**Comment by marckinson** [comment]
Hi, I am also getting the same error. Anyone could give a solution to this please ?
