### ISSUE TITLE
Unable to start validating peers

### ISSUE THREAD

**Issue by manjitguha** [IBM-Blockchain/ibm-blockchain-issues#78]
Hi Team,
I am unable to start validating peers for network ID "b34266ecc08a4699a00e9da5a5338f41". Please help.
Please find the log below. 
OUT - /scripts/start.sh -network_id b34266ecc08a4699a00e9da5a5338f41 -peer_id vp0 -chaincode_host prod-us-02-chaincode-swarm-vp0.us.blockchain.ibm.com -chaincode_port 3380 -network_name us.blockchain.ibm.com -port_discovery 30002 -port_rest 5002 -port_event 31002 -peer_enrollid peer0 -chaincode_tls true -peer_tls true -num_peers 4
OUT - Enrollment secret is not passed calculating the default
OUT - CORE_PEER_ID="vp0",CORE_PEER_NETWORKID="b34266ecc08a4699a00e9da5a5338f41",CORE_PEER_ADDRESSAUTODETECT="false",CORE_PEER_LISTENADDRESS="0.0.0.0:30002",CORE_REST_ADDRESS="0.0.0.0:5002",CORE_CLI_ADDRESS="0.0.0.0:30404",CORE_PEER_VALIDATOR_EVENTS_ADDRESS="0.0.0.0:31002",CORE_PEER_ADDRESS="b34266ecc08a4699a00e9da5a5338f41-vp0.us.blockchain.ibm.com:30002",CORE_LOGGING_PEER="warning",CORE_LOGGING_CRYPTO="warning",CORE_LOGGING_STATUS="warning",CORE_LOGGING_STOP="warning",CORE_LOGGING_LOGIN="warning",CORE_LOGGING_VM="debug",CORE_LOGGING_CHAINCODE="debug",CORE_PEER_LOGGING_LEVEL="warning",CORE_VM_ENDPOINT="tcp://prod-us-02-chaincode-swarm-vp0.us.blockchain.ibm.com:3380",CORE_VM_DOCKER_TLS_ENABLED="true",CORE_VM_DOCKER_TLS_CERT_FILE="/certs/chaincode_host/cert.pem",CORE_VM_DOCKER_TLS_KEY_FILE="/certs/chaincode_host/key.pem",CORE_VM_DOCKER_TLS_CA_FILE="/certs/chaincode_host/ca.pem",CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE="us.blockchain.ibm.com",CORE_PEER_TLS_ENABLED="true",CORE_PEER_TLS_CERT_FILE="/certs/peer/cert.pem",CORE_PEER_TLS_KEY_FILE="/certs/peer/key.pem",CORE_PEER_TLS_SERVERHOSTOVERRIDE="b34266ecc08a4699a00e9da5a5338f41-vp0.us.blockchain.ibm.com",CORE_PEER_PKI_TLS_ENABLED="true",CORE_PEER_PKI_TLS_ROOTCERT_FILE="/certs/peer/cert.pem",CORE_PEER_PKI_TLS_SERVERHOSTOVERRIDE="b34266ecc08a4699a00e9da5a5338f41-vp0.us.blockchain.ibm.com",CORE_PEER_DISCOVERY_PERIOD="60s",CORE_PEER_DISCOVERY_TOUCHPERIOD="60s",CORE_CHAINCODE_DEPLOYTIMEOUT="180000",CORE_CHAINCODE_STARTUPTIMEOUT="30000",CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN="pbft",CORE_PBFT_GENERAL_MODE="batch",CORE_PBFT_GENERAL_BATCHSIZE="1000",CORE_PBFT_GENERAL_TIMEOUT_BATCH="1s",CORE_PBFT_GENERAL_TIMEOUT_REQUEST="30s",CORE_PBFT_GENERAL_TIMEOUT_VIEWCHANGE="30s",CORE_PBFT_GENERAL_TIMEOUT_RESENDVIEWCHANGE="30s",CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST="0s",CORE_STATETRANSFER_TIMEOUT_SINGLEBLOCK="600s",CORE_STATETRANSFER_TIMEOUT_SINGLESTATEDELTA="600s",CORE_STATETRANSFER_TIMEOUT_FULLSTATE="600s",CORE_PEER_DISCOVERY_ROOTNODE="b34266ecc08a4699a00e9da5a5338f41-vp1.us.blockchain.ibm.com:30002,b34266ecc08a4699a00e9da5a5338f41-vp2.us.blockchain.ibm.com:30002,b34266ecc08a4699a00e9da5a5338f41-vp3.us.blockchain.ibm.com:30002",CORE_SECURITY_ENABLED="true",CORE_SECURITY_ENROLLID="peer0",CORE_SECURITY_ENROLLSECRET="6664830792",CORE_PEER_PKI_ECA_PADDR="b34266ecc08a4699a00e9da5a5338f41-ca.us.blockchain.ibm.com:30002",CORE_PEER_PKI_TCA_PADDR="b34266ecc08a4699a00e9da5a5338f41-ca.us.blockchain.ibm.com:30002",CORE_PEER_PKI_TLSCA_PADDR="b34266ecc08a4699a00e9da5a5338f41-ca.us.blockchain.ibm.com:30002"
OUT - 2016-12-05 12:04:45,757 CRIT Supervisor running as root (no user in config file)
OUT - 2016-12-05 12:04:45,759 INFO supervisord started with pid 14
OUT - 2016-12-05 12:04:46,761 INFO spawned: 'start_peer' with pid 17
OUT - 12:04:46.805 [nodeCmd] serve -> INFO 001[0m Security enabled status: true
OUT - 12:04:46.805 [nodeCmd] serve -> INFO 002[0m Privacy enabled status: false
OUT - 12:04:46.805 [eventhub_producer] start -> INFO 003[0m event processor started
OUT - 12:04:46.806 [db] open -> INFO 004[0m Setting rocksdb maxLogFileSize to 10485760
OUT - 12:04:46.806 [db] open -> INFO 005[0m Setting rocksdb keepLogFileNum to 10
OUT - 12:04:46.812 [crypto] RegisterValidator -> INFO 006[0m Registering validator [peer0] with name [peer0]...
OUT - 12:04:47.031 [crypto] RegisterValidator -> INFO 007[0m Registering validator [peer0] with name [peer0]...done!
OUT - 12:04:47.031 [crypto] InitValidator -> INFO 008[0m Initializing validator [peer0]...
OUT - 12:04:47.035 [crypto] InitValidator -> INFO 009[0m Initializing validator [peer0]...done!
OUT - 12:04:47.035 [chaincode] NewChaincodeSupport -> INFO 00a[0m Chaincode support using peerAddress: b34266ecc08a4699a00e9da5a5338f41-vp0.us.blockchain.ibm.com:30002
OUT - [33m12:04:47.035 [sysccapi] RegisterSysCC -> WARN 00b[0m Currently system chaincode does support security(noop,github.com/hyperledger/fabric/bddtests/syschaincode/noop)
OUT - 12:04:47.035 [state] loadConfig -> INFO 00c[0m Loading configurations...
OUT - 12:04:47.036 [state] loadConfig -> INFO 00d[0m Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[maxGroupingAtEachLevel:%!s(int=5) bucketCacheSize:%!s(int=100) numBuckets:%!s(int=1000003)], deltaHistorySize=[500]
OUT - 12:04:47.036 [state] NewState -> INFO 00e[0m Initializing state implementation [buckettree]
OUT - 12:04:47.036 [buckettree] initConfig -> INFO 00f[0m configs passed during initialization = map[string]interface {}{"maxGroupingAtEachLevel":5, "bucketCacheSize":100, "numBuckets":1000003}
OUT - 12:04:47.036 [buckettree] initConfig -> INFO 010[0m Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[5:1601 8:200001 3:65 9:1000003 7:40001 0:1 4:321 6:8001 2:13 1:3] hashFunc:0xab4dc0}
OUT - 12:04:47.036 [buckettree] newBucketCache -> INFO 011[0m Constructing bucket-cache with max bucket cache size = [100] MBs
OUT - 12:04:47.036 [buckettree] loadAllBucketNodesFromDB -> INFO 012[0m Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
OUT - 12:04:47.036 [genesis] func1 -> INFO 013[0m Creating genesis block.
OUT - 12:04:47.037 [consensus/controller] NewConsenter -> INFO 014[0m Creating consensus plugin pbft
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 015[0m PBFT type = *pbft.obcBatch
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 016[0m PBFT Max number of validating peers (N) = 4
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 017[0m PBFT Max number of failing peers (f) = 1
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 018[0m PBFT byzantine flag = false
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 019[0m PBFT request timeout = 30s
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01a[0m PBFT view change timeout = 30s
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01b[0m PBFT Checkpoint period (K) = 10
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01c[0m PBFT broadcast timeout = 1s
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01d[0m PBFT Log multiplier = 4
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01e[0m PBFT log size (L) = 40
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 01f[0m PBFT null requests disabled
OUT - 12:04:47.037 [consensus/pbft] newPbftCore -> INFO 020[0m PBFT automatic view change disabled
OUT - 12:04:47.037 [consensus/pbft] restoreLastSeqNo -> INFO 021[0m Replica 0 restored lastExec: 0
OUT - 12:04:47.037 [consensus/pbft] restoreState -> INFO 022[0m Replica 0 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqBatches: 0, chkpts: 1 h: 0
OUT - 12:04:47.037 [consensus/pbft] newObcBatch -> INFO 023[0m PBFT Batch size = 1000
OUT - 12:04:47.037 [consensus/pbft] newObcBatch -> INFO 024[0m PBFT Batch timeout = 1s
OUT - 12:04:47.038 [nodeCmd] serve -> INFO 025[0m Starting peer with ID=name:"vp0" , network ID=b34266ecc08a4699a00e9da5a5338f41, address=b34266ecc08a4699a00e9da5a5338f41-vp0.us.blockchain.ibm.com:30002, rootnodes=b34266ecc08a4699a00e9da5a5338f41-vp1.us.blockchain.ibm.com:30002,b34266ecc08a4699a00e9da5a5338f41-vp2.us.blockchain.ibm.com:30002,b34266ecc08a4699a00e9da5a5338f41-vp3.us.blockchain.ibm.com:30002, validator=true
OUT - 12:04:47.038 [consensus/statetransfer] blockThread -> INFO 026[0m Validated blockchain to the genesis block
OUT - 12:04:47.038 [consensus/statetransfer] SyncToTarget -> INFO 027[0m Syncing to target 46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762fd75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be for block number 0 with peers []
OUT - 12:04:47.038 [consensus/statetransfer] blockThread -> INFO 028[0m Validated blockchain to the genesis block
OUT - 12:04:47.038 [consensus/pbft] ProcessEvent -> INFO 029[0m Replica 0 application caught up via state transfer, lastExec now 0
OUT - 12:04:47.041 [rest] StartOpenchainRESTServer -> INFO 02a[0m Initializing the REST service on 0.0.0.0:5002, TLS is enabled.
OUT - [31m12:04:47.214 [peer] handleChat -> ERRO 02b[0m Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - [31m12:04:47.214 [peer] chatWithPeer -> ERRO 02c[0m Ending Chat with peer address b34266ecc08a4699a00e9da5a5338f41-vp1.us.blockchain.ibm.com:30002 due to error: Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - [31m12:04:47.220 [peer] handleChat -> ERRO 02d[0m Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - [31m12:04:47.220 [peer] chatWithPeer -> ERRO 02e[0m Ending Chat with peer address b34266ecc08a4699a00e9da5a5338f41-vp2.us.blockchain.ibm.com:30002 due to error: Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - [31m12:04:47.226 [peer] handleChat -> ERRO 02f[0m Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - [31m12:04:47.227 [peer] chatWithPeer -> ERRO 030[0m Ending Chat with peer address b34266ecc08a4699a00e9da5a5338f41-vp3.us.blockchain.ibm.com:30002 due to error: Error during Chat, stopping handler: rpc error: code = 9 desc = transport: received the unexpected content-type "text/html"
OUT - 2016-12-05 12:05:02,242 INFO success: start_peer entered RUNNING state, process has stayed up for > than 15 seconds (startsecs)
OUT - 2016/12/05 12:08:59 transport: http2Client.notifyError got notified that the client transport was broken read tcp 192.168.129.207:53134->169.46.12.196:30002: read: connection reset by peer.
OUT - 2016/12/05 12:08:59 transport: http2Client.notifyError got notified that the client transport was broken read tcp 192.168.129.207:53136->169.46.12.196:30002: read: connection reset by peer.
OUT - 2016/12/05 12:08:59 transport: http2Client.notifyError got notified that the client transport was broken read tcp 192.168.129.207:53138->169.46.12.196:30002: read: connection reset by peer.

Regards
Manjit

**Comment by altharp** [comment]
Based on checking the b34266ecc08a4699a00e9da5a5338f41 Blockchain network that was mentioned, it appears that all four validating peers are running but membership services is stopped.  First we would suggest trying to start membership services from the dashboard for the Blockchain network.

If a validating peer is not starting, we usually suggest a first step of determining if the peer can be started using the IBM Blockchain dashboard on Bluemix.

1.  Once you have logged into Bluemix, select your instance of the IBM Blockchain service and press the Launch button.
2.  Stop any validating peers that are running.
3.  Stop and then start Membership Services.
4.  Use the arrow button on the right to try starting the validating peer.
5.  If the validating peer does not start, go to the Logs tab and review the logs.

There are other possible causes of peers appearing to be stopped in the Blockchain Bluemix dashboard.

- Choosing the incognito or private browsing mode in a web browser could cause the peer to appear to be stopped.
- There could be a firewall setting that could prevent the browser from reaching the peers. You can try directly accessing a peer through a browser to determine if a firewall setting might be interfering. The address to use is in the following form: https://networkID-vp0.us.blockchain.ibm.com:5002/chain. The address prior to “chain” can be found in the **Routes** column of the **Network** tab of the IBM Blockchain service dashboard.

**Comment by vijaygopal** [comment]
Is this issue resolved ? I am facing the same issue. I tried the above approach and the peer's did not start.

**Comment by dhyey20** [comment]
@vijaygopal Please check if some firewall is blocking the ports. We have seen in many cases, firewall blocking the ports and peers/membership-services show as stopped.

**Comment by romanga** [comment]
I have same situation, tried stopping starting, validation nodes are stopped and nothing is being written to the log

**Comment by romanga** [comment]
today, miraculously, validating peers appeared to be online and running

**Comment by romanga** [comment]
logged in today, to find all VPs down, tried restarting with no luck, nothing in the logs

**Comment by dhyey20** [comment]
@romanga as per the comment earlier, it may be due to firewall blocking the ports. Please check if that is the case.

**Comment by dshuffma-ibm** [comment]
closed due to inactivity
