### ISSUE TITLE
Unable to start validating peers

### ISSUE THREAD

**Issue by mslangford** [IBM-Blockchain/ibm-blockchain-issues#80]
We recently discovered that the validating peers are stopped and are failing to restart. We restarted Membership Services but the validating peers still will not start. The network ID is 19cac554460e4b73b7acacf31ccfbedb.

Thanks
Matt

**Comment by dhyey20** [comment]
![image](https://cloud.githubusercontent.com/assets/9337987/21116576/1e444ad0-c084-11e6-9580-7d91ff5ad8ee.png)
We just checked and it seems all your peers are up.

**Comment by mslangford** [comment]
![screen shot 2016-12-12 at 1 26 50 pm](https://cloud.githubusercontent.com/assets/20495063/21117496/cb1dbbbc-c06e-11e6-9c8e-ea11858c9e0d.png)

Hmm, I just went in and looks like they are stopped.

**Comment by dhyey20** [comment]
We are using port `30003` as grpc and `5003` for http. It seems that `5003` has been blocked in your internet-network, but `30003` is not. Thats why you can see the Membership Services as up but the rest of the statuses don't update.

Are you aware of any firewalls in your network?

**Comment by mslangford** [comment]
Is there any way to change the port for http? I think in the past it was using 443.

Thanks
Matt

**Comment by dhyey20** [comment]
Yes, it was using 443 before. But sadly no, there is no way to change ports.

**Comment by mslangford** [comment]
Ok got it. Thanks!

**Comment by dhyey20** [comment]
Closing this. If you have any questions feel free to reopen.
