### ISSUE TITLE
Same Blockchain service - different service status for different users

### ISSUE THREAD

**Issue by debasisdas1976** [IBM-Blockchain/ibm-blockchain-issues#81]
#### I added my colleague to my project and asked her to check, and surprisingly she reported that she is able to see all the peers running.  When I go to deploy demo chaincode, I get the following error.
=========================================
Checking enroll id - Peer 2: dashboarduser_type1_2 ...
  ID not yet registered

Registering enroll id dashboarduser_type1_2 ...
  Error - failed to register enroll id

Checking enroll id - Peer 1: dashboarduser_type1_1 ...
  ID not yet registered

Registering enroll id dashboarduser_type1_1 ...
  Error - failed to register enroll id

Checking enroll id - Peer 0: dashboarduser_type1_0 ...
  ID not yet registered

Registering enroll id dashboarduser_type1_0 ...
  Error - failed to register enroll id
 
#### Error - cannot continue, failed to register enroll id! :(
        - make sure at least 1 peer is running. Then refresh the page and try again
=============================================

Where as, she is able to deploy demo chaincode. 

Any suggestions?

Regards
Debasis

**Comment by dhyey-ibm** [comment]
![image](https://cloud.githubusercontent.com/assets/24547445/21185400/8295a03c-c1de-11e6-8d67-6b488c58d6b6.png)
Yes, the peers and the membership service are running. When the demo tab tries to register users, it makes a grpc call to the peer on port 5003. I think the network you are in or your machine has this port blocked. Are you aware of any firewall in your network?

**Comment by debasisdas1976** [comment]
Thanks. That explains it. However I believe the dashboard should display some error showing that the port is blocked or "unable to communicate" instead of showing that the peers are not running. 
This is what I see.
<img width="939" alt="screen shot 2016-12-14 at 3 59 45 pm" src="https://cloud.githubusercontent.com/assets/8098513/21186944/832413c0-c216-11e6-8fd6-0708f83b4230.png">

**Comment by dhyey-ibm** [comment]
We will surely consider doing that if its feasible. But for now there is no way we can tell that the ports are blocked on the users end.

**Comment by dshuffma-ibm** [comment]
to reiterate, from the perspective of the monitor there is no difference between the peer being stopped or or unreachable (firewall problem). in both cases the api will time out.

potentially we can reword it from `stopped` to `unreachable`/`unknown`/`unresponsive` , but that's about all we could do.
