### ISSUE TITLE
Cannot register event client (GitHub block-listener example)

### ISSUE THREAD

**Issue by afried1** [IBM-Blockchain/ibm-blockchain-issues#83]
Cloned  hyperledger from GitHub
Cloned block-listener example from GitHub (examples/events/block-listener/block-listener.go)
Built block-listener, successfully on my local machine
When I start block-listener with the event port of any of my validating peers, I get the following error message:
D:\gotest\src>block-listener -events-address ...-vp3.us.blockchain.ibm.com:31003 -listen-to-rejections true -events-from-chaincode xyz
Event Address: ...-vp3.us.blockchain.ibm.com:31003
could not start chat timeout waiting for registration
Error creating event client

**Comment by dshuffma-ibm** [comment]
Sorry, but I have never used `block-listener`.  Nor has anyone that is watching this repo (that I know of)... 

You may have better luck on the Hyperledger Slack community. (hyperledgerproject.slack.com)
