### ISSUE TITLE
 failed to connect to 'ipv4:127.0.0.1:7054'

### ISSUE THREAD

**Issue by git123456** [IBM-Blockchain/ibm-blockchain-issues#88]
Hmm.. used to work but don't know why its no longer work.  

This is hfc 0.6.1
Docker client version is 1.11.2
Docker server version is 1.12.1

"docker ps" shown here :
7d31b5aa324d        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   About an hour ago   Up About an hour    0.0.0.0:7050-7051->7050-7051/tcp, 0.0.0.0:7053->7053/tcp   blockchain_vp0_1

a586149a96f0        hyperledger/fabric-membersrvc   "membersrvc"             About an hour ago   Up About an hour    0.0.0.0:7054->7054/tcp                                     blockchain_membersrvc_1

More detail error messages shown below :: 
E0119 03:28:03.925333000 123145321250816 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:7054': socket error: connection refused
E0119 03:28:04.929079000 123145321250816 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:7054': socket error: connection refused
E0119 03:28:06.529209000 123145321250816 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:7054': socket error: connection refused
E0119 03:28:08.912378000 123145321250816 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:7054': socket error: connection refused

**Comment by dhyey20** [comment]
Where are you running this docker containers? Is it on windows or linux?

**Comment by dshuffma-ibm** [comment]
closed due to inactivity
