### ISSUE TITLE
Unable to start - Validating Peer 0,1, 2 and 3 

### ISSUE THREAD

**Issue by sunilmis** [IBM-Blockchain/ibm-blockchain-issues#89]
When I log on dashboard I see only Membership Services	 is running and Validating Peer 0,1, 2 and 3 not running and I have tried to start Validating Peer 0 and see following message in logs and I am using BlueMix Service.

OUT - /scripts/start.sh -network_id 93c4d60ca5d34147900df6cb74073cfb -peer_id vp0 -chaincode_host prod-us-04-chaincode-swarm-vp0.us.blockchain.ibm.com -chaincode_port 3380 -network_name us.blockchain.ibm.com -port_discovery 30004 -port_rest 5004 -port_event 31004 -peer_enrollid peer0 -chaincode_tls true -peer_tls true -num_peers 4
OUT - Enrollment secret is not passed calculating the default
OUT - CORE_PEER_ID="vp0",CORE_PEER_NETWORKID="93c4d60ca5d34147900df6cb74073cfb",CORE_PEER_ADDRESSAUTODETECT="false",CORE_PEER_LISTENADDRESS="0.0.0.0:30004",CORE_REST_ADDRESS="0.0.0.0:5004",CORE_CLI_ADDRESS="0.0.0.0:30404",CORE_PEER_VALIDATOR_EVENTS_ADDRESS="0.0.0.0:31004",CORE_PEER_ADDRESS="93c4d60ca5d34147900df6cb74073cfb-vp0.us.blockchain.ibm.com:30004",CORE_LOGGING_PEER="warning",CORE_LOGGING_CRYPTO="warning",CORE_LOGGING_STATUS="warning",CORE_LOGGING_STOP="warning",CORE_LOGGING_LOGIN="warning",CORE_LOGGING_VM="debug",CORE_LOGGING_CHAINCODE="debug",CORE_PEER_LOGGING_LEVEL="warning",CORE_VM_ENDPOINT="tcp://prod-us-04-chaincode-swarm-vp0.us.blockchain.ibm.com:3380",CORE_VM_DOCKER_TLS_ENABLED="true",CORE_VM_DOCKER_TLS_CERT_FILE="/certs/chaincode_host/cert.pem",CORE_VM_DOCKER_TLS_KEY_FILE="/certs/chaincode_host/key.pem",CORE_VM_DOCKER_TLS_CA_FILE="/certs/chaincode_host/ca.pem",CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE="us.blockchain.ibm.com",CORE_PEER_TLS_ENABLED="true",CORE_PEER_TLS_CERT_FILE="/certs/peer/cert.pem",CORE_PEER_TLS_KEY_FILE="/certs/peer/key.pem",CORE_PEER_TLS_SERVERHOSTOVERRIDE="93c4d60ca5d34147900df6cb74073cfb-vp0.us.blockchain.ibm.com",CORE_PEER_PKI_TLS_ENABLED="true",CORE_PEER_PKI_TLS_ROOTCERT_FILE="/certs/peer/cert.pem",CORE_PEER_PKI_TLS_SERVERHOSTOVERRIDE="93c4d60ca5d34147900df6cb74073cfb-vp0.us.blockchain.ibm.com",CORE_PEER_DISCOVERY_PERIOD="60s",CORE_PEER_DISCOVERY_TOUCHPERIOD="60s",CORE_CHAINCODE_DEPLOYTIMEOUT="180000",CORE_CHAINCODE_STARTUPTIMEOUT="30000",CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN="pbft",CORE_PBFT_GENERAL_MODE="batch",CORE_PBFT_GENERAL_BATCHSIZE="1000",CORE_PBFT_GENERAL_TIMEOUT_BATCH="1s",CORE_PBFT_GENERAL_TIMEOUT_REQUEST="30s",CORE_PBFT_GENERAL_TIMEOUT_VIEWCHANGE="30s",CORE_PBFT_GENERAL_TIMEOUT_RESENDVIEWCHANGE="30s",CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST="0s",CORE_STATETRANSFER_TIMEOUT_SINGLEBLOCK="600s",CORE_STATETRANSFER_TIMEOUT_SINGLESTATEDELTA="600s",CORE_STATETRANSFER_TIMEOUT_FULLSTATE="600s",CORE_PEER_DISCOVERY_ROOTNODE="93c4d60ca5d34147900df6cb74073cfb-vp1.us.blockchain.ibm.com:30004,93c4d60ca5d34147900df6cb74073cfb-vp2.us.blockchain.ibm.com:30004,93c4d60ca5d34147900df6cb74073cfb-vp3.us.blockchain.ibm.com:30004",CORE_SECURITY_ENABLED="true",CORE_SECURITY_ENROLLID="peer0",CORE_SECURITY_ENROLLSECRET="42ff609d78",CORE_PEER_PKI_ECA_PADDR="93c4d60ca5d34147900df6cb74073cfb-ca.us.blockchain.ibm.com:30004",CORE_PEER_PKI_TCA_PADDR="93c4d60ca5d34147900df6cb74073cfb-ca.us.blockchain.ibm.com:30004",CORE_PEER_PKI_TLSCA_PADDR="93c4d60ca5d34147900df6cb74073cfb-ca.us.blockchain.ibm.com:30004"
OUT - 2017-01-18 23:42:18,241 CRIT Supervisor running as root (no user in config file)
OUT - 2017-01-18 23:42:18,243 INFO supervisord started with pid 14
OUT - 2017-01-18 23:42:19,245 INFO spawned: 'start_peer' with pid 17
OUT - 23:42:19.289 [nodeCmd] serve -> INFO 001[0m Security enabled status: true
OUT - 23:42:19.290 [eventhub_producer] start -> INFO 002[0m event processor started
OUT - 23:42:19.290 [nodeCmd] serve -> INFO 003[0m Privacy enabled status: false
OUT - 23:42:19.290 [db] open -> INFO 004[0m Setting rocksdb maxLogFileSize to 10485760
OUT - 23:42:19.291 [db] open -> INFO 005[0m Setting rocksdb keepLogFileNum to 10
OUT - 23:42:19.297 [crypto] RegisterValidator -> INFO 006[0m Registering validator [peer0] with name [peer0]...
OUT - 23:42:19.506 [crypto] RegisterValidator -> INFO 007[0m Registering validator [peer0] with name [peer0]...done!
OUT - 23:42:19.506 [crypto] InitValidator -> INFO 008[0m Initializing validator [peer0]...
OUT - 23:42:19.510 [crypto] InitValidator -> INFO 009[0m Initializing validator [peer0]...done!
OUT - 23:42:19.510 [chaincode] NewChaincodeSupport -> INFO 00a[0m Chaincode support using peerAddress: 93c4d60ca5d34147900df6cb74073cfb-vp0.us.blockchain.ibm.com:30004
OUT - [33m23:42:19.510 [sysccapi] RegisterSysCC -> WARN 00b[0m Currently system chaincode does support security(noop,github.com/hyperledger/fabric/bddtests/syschaincode/noop)
OUT - 23:42:19.510 [state] loadConfig -> INFO 00c[0m Loading configurations...
OUT - 23:42:19.510 [state] loadConfig -> INFO 00d[0m Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[bucketCacheSize:%!s(int=100) numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5)], deltaHistorySize=[500]
OUT - 23:42:19.510 [state] NewState -> INFO 00e[0m Initializing state implementation [buckettree]
OUT - 23:42:19.510 [buckettree] initConfig -> INFO 00f[0m configs passed during initialization = map[string]interface {}{"bucketCacheSize":100, "numBuckets":1000003, "maxGroupingAtEachLevel":5}
OUT - 23:42:19.510 [buckettree] initConfig -> INFO 010[0m Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[3:65 0:1 8:200001 7:40001 6:8001 5:1601 4:321 2:13 1:3 9:1000003] hashFunc:0xab4dc0}
OUT - 23:42:19.510 [buckettree] newBucketCache -> INFO 011[0m Constructing bucket-cache with max bucket cache size = [100] MBs
OUT - 23:42:19.510 [buckettree] loadAllBucketNodesFromDB -> INFO 012[0m Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
OUT - 23:42:19.510 [genesis] func1 -> INFO 013[0m Creating genesis block.
OUT - 23:42:19.511 [consensus/controller] NewConsenter -> INFO 014[0m Creating consensus plugin pbft
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 015[0m PBFT type = *pbft.obcBatch
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 016[0m PBFT Max number of validating peers (N) = 4
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 017[0m PBFT Max number of failing peers (f) = 1
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 018[0m PBFT byzantine flag = false
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 019[0m PBFT request timeout = 30s
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01a[0m PBFT view change timeout = 30s
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01b[0m PBFT Checkpoint period (K) = 10
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01c[0m PBFT broadcast timeout = 1s
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01d[0m PBFT Log multiplier = 4
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01e[0m PBFT log size (L) = 40
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 01f[0m PBFT null requests disabled
OUT - 23:42:19.512 [consensus/pbft] newPbftCore -> INFO 020[0m PBFT automatic view change disabled
OUT - 23:42:19.512 [consensus/pbft] restoreLastSeqNo -> INFO 021[0m Replica 0 restored lastExec: 0
OUT - 23:42:19.512 [consensus/pbft] restoreState -> INFO 022[0m Replica 0 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqBatches: 0, chkpts: 1 h: 0
OUT - 23:42:19.512 [consensus/pbft] newObcBatch -> INFO 023[0m PBFT Batch size = 1000
OUT - 23:42:19.512 [consensus/pbft] newObcBatch -> INFO 024[0m PBFT Batch timeout = 1s
OUT - 23:42:19.512 [nodeCmd] serve -> INFO 025[0m Starting peer with ID=name:"vp0" , network ID=93c4d60ca5d34147900df6cb74073cfb, address=93c4d60ca5d34147900df6cb74073cfb-vp0.us.blockchain.ibm.com:30004, rootnodes=93c4d60ca5d34147900df6cb74073cfb-vp1.us.blockchain.ibm.com:30004,93c4d60ca5d34147900df6cb74073cfb-vp2.us.blockchain.ibm.com:30004,93c4d60ca5d34147900df6cb74073cfb-vp3.us.blockchain.ibm.com:30004, validator=true
OUT - 23:42:19.512 [consensus/statetransfer] blockThread -> INFO 026[0m Validated blockchain to the genesis block
OUT - 23:42:19.513 [consensus/statetransfer] SyncToTarget -> INFO 027[0m Syncing to target 46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762fd75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be for block number 0 with peers []
OUT - 23:42:19.513 [consensus/statetransfer] blockThread -> INFO 028[0m Validated blockchain to the genesis block
OUT - 23:42:19.513 [consensus/pbft] ProcessEvent -> INFO 029[0m Replica 0 application caught up via state transfer, lastExec now 0
OUT - 23:42:19.518 [rest] StartOpenchainRESTServer -> INFO 02a[0m Initializing the REST service on 0.0.0.0:5004, TLS is enabled.
OUT - [31m23:42:22.515 [peer] chatWithPeer -> ERRO 02b[0m Error creating connection to peer address 93c4d60ca5d34147900df6cb74073cfb-vp1.us.blockchain.ibm.com:30004: grpc: timed out when dialing
OUT - [31m23:42:22.516 [peer] chatWithPeer -> ERRO 02c[0m Error creating connection to peer address 93c4d60ca5d34147900df6cb74073cfb-vp3.us.blockchain.ibm.com:30004: grpc: timed out when dialing
OUT - 2017-01-18 23:42:34,527 INFO success: start_peer entered RUNNING state, process has stayed up for > than 15 seconds (startsecs)
OUT - [31m23:43:19.751 [peer] handleChat -> ERRO 02d[0m Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp3"  93c4d60ca5d34147900df6cb74073cfb-vp3.us.blockchain.ibm.com:30004 VALIDATOR ��(�զӍ�:�~:1���S�lh\ş��}

**Comment by dhyey20** [comment]
![image](https://cloud.githubusercontent.com/assets/9337987/22123496/cd986636-de59-11e6-907e-317b4008367d.png)

**Comment by dhyey20** [comment]
It seems that all your peers are up. Check this: https://developer.ibm.com/answers/questions/328268/why-does-the-blockchain-starter-plan-network-dashb/?smartspace=blockchain
@sunilmis

**Comment by sunilmis** [comment]
![err](https://cloud.githubusercontent.com/assets/7231100/22123713/af3e12d4-de5a-11e6-8624-305a75437ca1.png)

Sorry I am not sure if I have same issue.. If I am using bluemix then where I should check the block ports?

**Comment by sunilmis** [comment]
Thanks! got it working.
