### ISSUE TITLE
Unable to Query peer after stop and start

### ISSUE THREAD

**Issue by lhaskins** [IBM-Blockchain/ibm-blockchain-issues#9]
On the `ba85c7ce-94bc-4488-a3e4-fbfbbbac7e0d` BlueMix network, the following consensus test was executed:

1. Deploy example2 chaincode (a=2100; b=2400)
2. Query all 4 peers -> verify they all return the same values (b=2400)
3. Invoke 3 times.
4. Query all 4 peers -> verify they all return the same values (b=2430)
5. Stop vp1
6. Invoke 2 times. (vp0, vp3)
7. Query all 4 peers -> verify vp0, vp2, vp3 return correct values (b=2450); vp1 returns `503 Service Unavailable`
8. Stop vp2
9. Invoke 6 times.
10. Query all 4 peers -> verify vp0, vp3 return same values (b=2450); vp1 and vp2 returns `503 Service Unavailable`
11. Start vp1 (wait)
12. Once vp1 is back, query all 4 peers -> verify vp0, vp3 return correct values (b=2510); **vp1 (and vp2) returns `503 Service Unavailable`**

While consensus is reinstated once vp1 is restarted, a query still showed 503. Calling the `network/peers` returned the correct list of peers. We waited for more than 15 minutes for the peer to not return a `503` response.

**Comment by lhaskins** [comment]
We continued and brought back up the 4th peer and queried the peer with the same `503 Service Unavailable` response. 

After a "forced reload of the proxy", the peers came back up. On vp1, a query returned with a `Registration missing` response for vp1. After registering a new user, the query completed successfully with the correct value. 

About 20 minutes later, on vp2, there was no registration problem and the query worked.

**Comment by lhaskins** [comment]
It should be noted, that the same problem occurs when bringing only 1 peer down and back up again.

**Comment by weedcocco** [comment]
We would like to have this retested please-- i sent notes.

**Comment by lhaskins** [comment]
The issue still exists. I waited for 5 minutes after performing the invokes before executing a query on the stopped peer. I retested on a new network: `c7ff36d1-c367-40d4-84cf-4e1f6c7de001`

![image](https://cloud.githubusercontent.com/assets/5166016/17305753/136133e6-57fa-11e6-9bfc-7abbc238ffde.png)

![screenshot from 2016-08-01 15 08 04](https://cloud.githubusercontent.com/assets/5166016/17305735/f5ea4244-57f9-11e6-802e-735278602a3d.png)

**Comment by lhaskins** [comment]
Verified this issue was fixed as of 11am EST today.
