### ISSUE TITLE
getting error while deploying chain code

### ISSUE THREAD

**Issue by aishwaryanit** [IBM-Blockchain/ibm-blockchain-issues#90]
in the 7th step of help using blockchain service im getting errors in postman can u send me code

**Comment by mrshah-at-work** [comment]
Can you paste the error that you are getting?

**Comment by aishwaryanit** [comment]
"code":-32700,
"message": "Parse error",
"data": "Error unmarshalling chaincode request payload: invalid  character
 'P' looking for beginning of value"

**Comment by masterDev1985** [comment]
Sounds like we might be able to diagnose the issue if we could see the body of the request you sent in Postman.  @aishwaryanit post that here, please.

**Comment by aishwaryanit** [comment]
I have copied and pasted same code as given in  step7 of recipe tutorials
hello world using blockchain part1 in the postman

On 20 Jan 2017 19:36, "Dale Avery" <notifications@github.com> wrote:

Sounds like we might be able to diagnose the issue if we could see the body
of the request you sent in Postman. @aishwaryanit
<https://github.com/aishwaryanit> post that here, please.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/IBM-Blockchain/ibm-blockchain-issues/issues/90#issuecomment-274079535>,
or mute the thread

**Comment by aishwaryanit** [comment]
Payload

{



  “jsonrpc”: “2.0”,



  “method”: “deploy”,



  “params”: {



    “type”: 1,



    “chaincodeID”: {



      “path”: “https://github.com/AmarMundi/learn-chaincode/finished”



    },

    “ctorMsg”: {

      “function”: “init”,

      “args”: [

            “hello_world”

    ]

    },



    “secureContext”: “user_type1_0”



  },



  “id”: 1



}

**Comment by masterDev1985** [comment]
```
{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID": {
      "path": "https://github.com/<YOUR_GITHUB_ID_HERE>/learn-chaincode/finished"
    },
    "ctorMsg": {
      "function": "init",
      "args": [
        "hi there"
      ]
    },
    "secureContext": "<YOUR_USER_HERE>"
  },
  "id": 1
}
```

When I pasted your payload into a JSON formatter, I received an error.  The one from the tutorial, which I copied above, seems to work.  I can't spot the formatting differences between the two, but there must be one.  You mind recopying the payload and trying again?  Your payload should look like this one.

```
{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID": {
      "path": "https://github.com/AmarMundi/learn-chaincode/finished"
    },
    "ctorMsg": {
      "function": "init",
      "args": [
        "hello_world"
      ]
    },
    "secureContext": "user_type1_0"
  },
  "id": 1
}
```

**Comment by aishwaryanit** [comment]
I tried im not getting... wether i should install ma own go and github
account? So that it comes in ma local machine?

**Comment by masterDev1985** [comment]
You mentioned that you were using Postman.  That second block that I posted should have the correct request payload that you should send to the chaincode endpoint using Postman.

**Comment by aishwaryanit** [comment]
Just can you explain what should be in path of request

**Comment by masterDev1985** [comment]
It should be a POST request to `https://<peer_host>:<peer_port>/chaincode`.  I grabbed a service instance on Bluemix so I could show you and example url:
```
https://f407f6a23a9f4e6786f3d97f8781bb61-vp0.us.blockchain.ibm.com:5004/chaincode
```
It also occurred to me that you could be talking about the `path` field of the request payload.  Your path should be
```
https://github.com/aishwaryanit/learn-chaincode/finished
```

**Comment by princeoftides** [comment]
Hi, I can deploy my learn-chaincode sample from my github url fine: 
"path": "https://github.com/princeoftides/learn-chaincode/finished"
But can I also deploy from my github V2.0 branch? 
 “path”: “https://github.com/princeoftides/learn-chaincode/blob/v2.0/start”
I get this error:
Response Body
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Deployment failure",
    "data": "Error when deploying chaincode: Error getting chaincode package bytes: Error getting code 'go get' failed with error: \"exit status 1\"\npackage github.com/princeoftides/learn-chaincode/blob/v2.0/start: cannot find package \"github.com/princeoftides/learn-chaincode/blob/v2.0/start\" in any of:\n\t/opt/go/src/github.com/princeoftides/learn-chaincode/blob/v2.0/start (from $GOROOT)\n\t/opt/gopath/_usercode_/945117110/src/github.com/princeoftides/learn-chaincode/blob/v2.0/start (from $GOPATH)\n\t/opt/gopath/src/github.com/princeoftides/learn-chaincode/blob/v2.0/start\n"
  },
  "id": 0
}

**Comment by masterDev1985** [comment]
@princeoftides the peer is using a `go get` command to pull your code from github.  Unfortunately, this command doesn't support branch information in the url.  It always pulls from the master branch of the repository.  One way around this is to use [gopkg.in](http://labix.org/gopkg.in) to create a url that will let `go get` pull a specific branch of your code.  Check my work, but I believe your gopkg.in url would be: `gopkg.in/princeoftides/learn-chaincode.v2/finished`
