### ISSUE TITLE
Error:Failed to launch chaincode spec(Could not get deployment transaction for 

### ISSUE THREAD

**Issue by leobekhuis** [IBM-Blockchain/ibm-blockchain-issues#91]
Hi I am running into some problems with querying chaincode_example02.

[hfc] Now we are enrolling admin ...
[hfc] Enrolled John Doe successfully
[hfc] Deploying chaincode; please wait ...
[hfc] Deploy complete; results: {"uuid":"xxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617","chaincodeID":"xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617"}
[hfc] Invoke chaincode ...
[hfc] Invoke submitted successfully; results={"uuid":"e18485b6-f51e-43b2-8116-a98f01b7bdc9"}
[hfc] Invoke completed successfully; results={"result":"Tx e18485b6-f51e-43b2-8116-a98f01b7bdc9 complete"}
[hfc] Querying the chaincode ...
--------> Failed to query chaincode: request=

 msg: 'Error:Failed to launch chaincode spec(Could not get deployment transaction for xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617 - LedgerError - ResourceNotFound: ledger: resource not found)' }

when i look at the peer log I see different things which I want to get clarified;

_first question is about the peer and shim import, do I need to add them into my go working directory on the server?_

_second is about: could not recreate container API error (500): Error: image library/8b01ce9efeff42d48ce02c3c53356c1d-vp0-xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617:latest not found

could someone please tell me what is going on or tell where to look for getting this solved?_

OUT - 20:45:56.877 [consensus/pbft] ProcessEvent -> INFO 1ca[0m Replica 0 batch timer expired
OUT - 20:45:56.877 [consensus/pbft] sendBatch -> INFO 1cb[0m Creating batch with 1 requests
OUT - 20:45:56.879 [consensus/pbft] executeOne -> INFO 1cc[0m Replica 0 executing/committing request batch for view=0/seqNo=31 and digest YrYAFLUeCUaZSwV85WOvOzd8rDHIeryEt5612Tck8gjf+jVU+Xh1y+3OE+rpz08VPPSbbwt7vR0wsrU1NzvXoA==
OUT - [31m20:45:58.930 [dockercontroller] deployImage -> ERRO 1cd[0m Error building images: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617' returned a non-zero code: 1
OUT - [31m20:45:58.930 [dockercontroller] deployImage -> ERRO 1ce[0m Image Output:
OUT - ********************
OUT - Step 1 : FROM hyperledger/fabric-baseimage
OUT -  ---> 21cb00fb27f4
OUT - Step 2 : COPY . $GOPATH/src/build-chaincode/
OUT -  ---> Using cache
OUT -  ---> f4e8d401945d
OUT - Step 3 : WORKDIR $GOPATH
OUT -  ---> Using cache
OUT -  ---> 4cb1d635a080
OUT - Step 4 : RUN go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617
OUT -  ---> Running in 85da9ebe80f0
OUT - [91msrc/build-chaincode/chaincode_example02.go:30:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
OUT - 	/opt/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
OUT - 	/opt/gopath/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
OUT - [0m
OUT - ********************
OUT - [31m20:45:59.688 [dockercontroller] Start -> ERRO 1cf[0m start-could not recreate container API error (500): Error: image library/8b01ce9efeff42d48ce02c3c53356c1d-vp0-xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617:latest not found
OUT - [31m20:45:59.688 [chaincode] Launch -> ERRO 1d0[0m launchAndWaitForRegister failed Error starting container: API error (500): Error: image library/8b01ce9efeff42d48ce02c3c53356c1d-vp0-xxxxdb43feb10640d37c343bf6d50feb29ba21da196075a721d6489eb1fab617:latest not found
OUT - 20:45:59.689 [consensus/pbft] execDoneSync -> INFO 1d1[0m Replica 0 finished execution 31, trying next
OUT - 20:47:56.546 [consensus/pbft] ProcessEvent -> INFO 1d2[0m Replica 0 batch timer expired
OUT - 20:47:56.547 [consensus/pbft] sendBatch -> INFO 1d3[0m Creating batch with 1 requests
OUT - 20:47:56.548 [consensus/pbft] executeOne -> INFO 1d4[0m Replica 0 executing/committing request batch for view=0/seqNo=32 and digest HfK1r9YKy8VyEKJPyWbRITJalorskEzDb9xuxqsLvBQNWw1ePsH6W4NZtBHmm+Wgo5Q2TgumvLpApyPSvD5xWQ==
OUT - 20:47:56.549 [consensus/pbft] execDoneSync -> INFO 1d5[0m Replica 0 finished execution 32, trying next

**Comment by akshay111meher** [comment]
docker container must have file $GOPATH/src/github.com/hyperledger/fabric/protos/peer..
it is missing....
docker must be updated

**Comment by dshuffma-ibm** [comment]
closed due to inactivity
