### ISSUE TITLE
Question about editing my own Blockchain chaincode

### ISSUE THREAD

**Issue by qianlizimu** [IBM-Blockchain/ibm-blockchain-issues#92]
After I ran the Marbles Demo of IBM Blockchain, I tried editing its chaincode. For example, I changed the attributes of the struct "Marble" from {name, size, color, user} to {name, price, user}. And I have edited the jade file and Javascript file based on my new chaincode. At last I found the revised chaincode failed to work and the program seemed not able to connect the blockchain network. (I tried it both on Bluemix and on Docker)
I noticed that in the "app.js" file of the Marbles project there are some settings as following: (line 226 to line 229)
--------------------- 
chaincode:{
zip_url: 'https://github.com/ibm-blockchain/marbles/archive/v2.0.zip',
unzip_dir: 'marbles-2.0/chaincode',													
git_url: 'http://gopkg.in/ibmblockchain/marbles.v2/chaincode',							
}
---------------------
Should I change the values of "zip_url","unzip_dir" and "git_url"? Thanks!

**Comment by dshuffma-ibm** [comment]
Yes. 

Those 3 fields must be changed to reference your chaincode repository.

**Comment by qianlizimu** [comment]
@dshuffma-ibm  Thank you! When I deploy the project on Bluemix, I found the git url such as "https://hub.jazz.net/git/chain0209/marbles-chain0209-1645", but how to decide the zip_url? Thanks again.

**Comment by dhyey20** [comment]
![image](https://cloud.githubusercontent.com/assets/9337987/24250056/e984eb5c-0fab-11e7-9869-2c58e9570ab6.png)
In github, if you make a release/tag and then go to the releases page, you will see the source zip link.

**Comment by dshuffma-ibm** [comment]
closed due to inactivity
