### ISSUE TITLE
On Blumix Blockchain Service is not working

### ISSUE THREAD

**Issue by SarfarazPathan** [IBM-Blockchain/ibm-blockchain-issues#96]
When trying to access Blockchain service we are getting below error in Bluemix

This network does not exist
ID: bb650ea4-9c1f-4296-9d16-b12662686b00

**Comment by mrshah-at-work** [comment]
Looks like your network was too hold and not being used for a long time. Can you please go ahead and create a new network.

**Comment by SarfarazPathan** [comment]
Thanks Mihir ,

Seems that was only issue as from long time i have not used this service.

I have created not Blockchain Service and redeployed chain code now it is
working.

Thanks & Regards
Sarfaraz

**Comment by SarfarazPathan** [comment]
After creating new Block chain service issue resolved
